<?php if(isset($this->session->user)){?>
<script>
	window.location = '/public/home';
</script>
<?php }else{?>
<style type="text/css">

.signinLabel{
	font-size: 14px;
	font-weight: bold;
	margin-bottom: 5px;
}

#signinCheckbox{
	margin-top: 10px;
}

#forgotPassword{
	color: #0091ea;
}
</style>
<div style="margin-top: 65px;">
	<form class="form-signin" method="post" action="index" onsubmit='return validation();'>
	<div id="sign-in"><h4 class="form-signin-heading" style="text-align: center;">SIGN IN</h4></div>
	<hr>
	<?php if (isset($this->errors)){?>
		<div class="alert alert-error" id="login-form-error"><?php echo $this->errors['invalid_credentials'];?> </div>
	<?php }?>
	<div class="alert alert-error" id="login-form-error" style="display: none;"> </div>
	<label for="username" class="signinLabel" style="text-align: center;">USER NAME</label>
	<input type="text" id="username" name="username" class="input-block-level" placeholder="Username"> 
	<label for="password" class="signinLabel"  style="text-align: center;">PASSWORD</label>
	<input type="password" id="password" name="password" class="input-block-level" placeholder="Password"> 
	<div style="height: 15px">&nbsp;</div>
	<input class="btn btn-block btn-primary" type="submit" name="submit" value="SIGN IN" style="height: 38px">
	<!-- <label class="checkbox" id="signinCheckbox"> <input type="checkbox" value="remember-me">
		Remember me
	</label> -->
	<div style="text-align: center;padding-top: 18px;"><label id="forgotPassword" >Forgot Password?</label></div>
	
</form>
</div>
<?php }?>

<script>
function validation(){
	var error = false;
	if($('#username').val() == "" || $('#password').val() == "" ){
		error = true;
	}
	if(!error){
		return true;
	}else{
		$("#login-form-error").css("display", "block");
		$('#login-form-error').html('Please enter valid Username/Password');
		return false;
	}
}
</script>

