<?php if(isset($this->session->user)){?>
<script>
	window.location = '/public/home';
</script>
<?php }else{?>
<style type="text/css">
body {
	background-color: #f5f5f5;
}

.signinLabel{
	font-size: 14px;
	font-weight: bold;
	margin-bottom: 5px;
}

#signinCheckbox{
	margin-top: 10px;
}

#forgotPassword{
	color: #0091ea;
}
</style>
   
<form class="form-signin" method="post" action="index" onsubmit='return validation();'>
	<h4 class="form-signin-heading" style="text-align: center;">SIGN IN</h4>
	<hr>
	<?php if (isset($this->errors)){?>
		<div class="alert alert-error" id="login-form-error"><?php echo $this->errors['invalid_credentials'];?> </div>
	<?php }?>
	<div class="alert alert-error" id="login-form-error" style="display: none;"> </div>
	<label for="username" class="signinLabel">USER NAME</label>
	<input type="text" id="username" name="username" class="input-block-level" placeholder="Username"> 
	<label for="password" class="signinLabel">PASSWORD</label>
	<input type="password" id="password" name="password" class="input-block-level" placeholder="Password"> 
	<input class="btn btn-block btn-primary" type="submit" name="submit" value="Sign In">
	<label class="checkbox" id="signinCheckbox"> <input type="checkbox" value="remember-me">
		Remember me
	</label>
	<label id="forgotPassword" >Forgot Password?</label>
	
</form>
<?php }?>

<script>
function validation(){
	var error = false;
	if($('#username').val() == "" || $('#password').val() == "" ){
		error = true;
	}
	if(!error){
		return true;
	}else{
		$("#login-form-error").css("display", "block");
		$('#login-form-error').html('Please enter valid Username/Password');
		return false;
	}
}
</script>

