<?php if(isset($this->session->user)){?>
<script>
	window.location = '/public/home';
</script>
<?php }else{?>
<style type="text/css">
body {
	background-color: #f5f5f5;
}
</style>
   
<form class="form-signin" method="post" action="index" onsubmit='return validation();'>
	<h3 class="form-signin-heading">Sign In</h3>
	<?php if (isset($this->errors)){?>
		<div class="alert alert-error" id="login-form-error"><?php echo $this->errors['invalid_credentials'];?> </div>
	<?php }?>
	<div class="alert alert-error" id="login-form-error" style="display: none;"> </div>
	<input type="text" id="username" name="username" class="input-block-level" placeholder="Username"> 
	<input type="password" id="password" name="password" class="input-block-level" placeholder="Password"> 
	<label class="checkbox"> <input type="checkbox" value="remember-me">
		Remember me
	</label>
	<input class="btn btn-primary" type="submit" name="submit" value="Sign In">
</form>
<?php }?>

<script>
function validation(){
	var error = false;
	if($('#username').val() == "" || $('#password').val() == "" ){
		error = true;
	}
	if(!error){
		return true;
	}else{
		$("#login-form-error").css("display", "block");
		$('#login-form-error').html('Please enter valid Username/Password');
		return false;
	}
}
</script>

