<div id="error_message" class="alert alert-error" <?php echo !empty($this->response['status']) && $this->response['status'] == 0 ? "" : "style='display: none;'"?>></div>
<!-- templates -->
<div style="display: none;">
	<select name="state" id="state_template" >
		<option value="0">--Select--</option>
		<?php foreach ($this->states as $state){?>
	  	<option value="<?php echo $state['id']?>"><?php echo $state['name']?></option>
	  	<?php }?>
	</select>
</div>
<!-- templates -->
<form action="iec/editiec" method="post" name="iec_form" id="iec_form" enctype="multipart/form-data"> 
	<table class="table table-bordered" style="width: 950px">
		<caption style="height: 30px">
				<strong>APPLICATION FORM FOR ISSUE/MODIFICATION IN IMPORTER EXPORTER CODE (IEC) NUMBER</strong>
		</caption>
		<tr>
			<td>
				<ul>
					<li>Please read the detailed guidelines befre filling up his form <br />
						Click here to read the guidelines
					</li>
					<li>Click here for information about requisite documents to be
						uploaded <br /> The documents should be uploaded in digital forma
						- GIF, <br /> JPEG size not exceeding 5MB
					</li>
					<li>Ensure that the requisite documents are legible before uploading</li>
				</ul>
			</td>
			<td style="width: 150px; height: 140px;">
				 <div class="image-upload">
				    <label for="user_image_file" style="margin: 0px 0px">
				        <img id="user_images" style="width: 140px; height: 140px;" src="user_images/<?php echo !empty($this->iec_info['image'])? $this->iec_info['image'] : "image.png"?>" class="img-polaroid">
				    </label>
				    <input id="user_image_file" name="user_image_file" type="file" accept="image/gif, image/jpeg, image/png" onchange="readURL(this);"/>
				</div>
			</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<caption style="height: 30px">
			<strong>Applicant Details <input class="input-block-level" type="hidden"  name="iec_id" id="iec_id" value="<?php echo !empty($_GET['id'])? $_GET['id'] : ""?>" ></strong>
		</caption>
		<tr class="info">
			<td colspan="5">Part A:  </td>
		</tr>
		<tr>
			<td colspan="2">IEC Number</td>
			<td colspan="3"><input type="text" class="input-block-level" value="<?php echo !empty($this->iec_info['iec_number'])? $this->iec_info['iec_number'] : ""?>" /></td>
		</tr>
		<tr>
			<td colspan="2">i. Name of entity in whose name IEC is required<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Name of entity" name="entity[name]" id="entity_name" value="<?php echo !empty($this->iec_info['name'])? $this->iec_info['name'] : ""?>"></td>
		</tr>
		<tr>
			<td rowspan="4" width="225px">ii. Address:</td>
			<td colspan="1" width="130px">Flat/Plot/Block No:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Flat/Plot/Block No" name="entity[address1]" id="entity_address1" value="<?php echo !empty($this->iec_info['address1'])? $this->iec_info['address1'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="1">Street/Area/Locality:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Street/Area/Locality" name="entity[address2]" id="entity_address2" value="<?php echo !empty($this->iec_info['address2'])? $this->iec_info['address2'] : ""?>"></td>
		</tr>
		<tr>
			<td>State:<span class="required">*</span></td>
			<td>
				<select name="entity[state]" id="entity_state" class="state_selectbox">
					<option value="0">--Select--</option>
					<?php foreach ($this->states as $state){
							$state_selected =  "";
							if (!empty($this->iec_info['state']) && $this->iec_info['state'] == $state['id']){
								$state_selected =  "selected = selected";
							}
						?>
				  	<option value="<?php echo $state['id']?>" <?php echo $state_selected;?>><?php echo $state['name']?></option>
				  	<?php }?>
				</select>
			</td>
			<td>District:<span class="required">*</span></td>
			<td>
				<select name="entity[district]" id="entity_district" class="district_selectbox">
					<option value="0">--Select--</option>
					<?php foreach ($this->districts as $district){
							$district_selected =  "";
							if (!empty($this->iec_info['district']) && $this->iec_info['district'] == $district['id']){
								$district_selected =  "selected = selected";
							}
						?>
				  	<option value="<?php echo $district['id']?>" <?php echo $district_selected;?>><?php echo $district['name']?></option>
				  	<?php }?>
				</select>
			</td>
		</tr>
		<tr>
			<td>City:<span class="required">*</span></td>
			<td>
				<select name="entity[city]" id="entity_city" class="city_selectbox">
					<option value="0">--Select--</option>
					<?php foreach ($this->cities as $city){
							$city_selected =  "";
							if (!empty($this->iec_info['city']) && $this->iec_info['city'] == $city['id']){
								$city_selected =  "selected = selected";
							}
						?>
				  	<option value="<?php echo $city['id']?>" <?php echo $city_selected;?>><?php echo $city['name']?></option>
				  	<?php }?>
				</select>
			</td>
			<td>Pincode:<span class="required">*</span></td>
			<td><input class="input-block-level" type="text" placeholder="Pincode" name="entity[pincode]" id="entity_pincode" value="<?php echo !empty($this->iec_info['pincode'])? $this->iec_info['pincode'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="2">iii. Landline telephone no., if any (wih area code):</td>
			<td colspan="3"><input class="input-xlarge" type="text" placeholder="Landline" name="entity[telephone]" id="entity_telephone" value="<?php echo !empty($this->iec_info['telephone'])? $this->iec_info['telephone'] : ""?>"></td>
		</tr>
		<tr>
			<td rowspan="2" colspan="2">iv. Mobile No:</td>
			<td>Primary Mobile No:<span class="required">*</span></td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Primary Mobile No" name="entity[mobile1]" id="entity_mobile1" value="<?php echo !empty($this->iec_info['mobile1'])? $this->iec_info['mobile1'] : ""?>"></td>
		</tr>
		<tr>
			<td>Other Mobile No:, if any:</td>
			<td colspan="2"><input class="input-block-level" type="text"	placeholder="Other Mobile No" name="entity[mobile2]" id="entity_mobile2" value="<?php echo !empty($this->iec_info['mobile2'])? $this->iec_info['mobile2'] : ""?>"></td>
		</tr>
		<tr>
			<td rowspan="4" colspan="2">v. Email ID/Website Address:</td>
			<td>Primary Email ID:<span class="required">*</span></td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Primary Email ID" name="entity[email1]" id="entity_email1" value="<?php echo !empty($this->iec_info['email1'])? $this->iec_info['email1'] : ""?>"></td>
		</tr>
		<tr>
			<td>Alternate Email ID:</td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Alternate Email ID" name="entity[email2]" id="entity_email2" value="<?php echo !empty($this->iec_info['email2'])? $this->iec_info['email2'] : ""?>"></td>
		</tr>
		<tr>
			<td>Website(if any):</td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Website" name="entity[website]" id="entity_website" value="<?php echo !empty($this->iec_info['website'])? $this->iec_info['website'] : ""?>"></td>
		</tr>
		<tr>
			<td>FAX No:(if any, with area code)</td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="FAX No" name="entity[fax]" id="entity_fax" value="<?php echo !empty($this->iec_info['fax'])? $this->iec_info['fax'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="2">vi. Nature of concern/entity:<span class="required">*</span></td>
			<td colspan="3">
				<div id="categories_section_select_check"></div>
				<?php foreach ($this->entity_categories as $categories){
						$category_checked =  "";
							if (!empty($this->iec_info['category']) && $this->iec_info['category'] == $categories['id']){
								$category_checked =  "checked = checked";
							}
						?>
				<label class="radio"><input type="radio" name="entity[category]" value="<?php echo $categories['id']?>" class="firm_<?php echo $categories['classname']?>" <?php echo $category_checked;?>><?php echo $categories['name']?></label> 
				<?php }?>
				<!-- <label class="radio"><input type="radio" name="entity_category" value="entity_partnership">Partnership</label> 
				<label class="radio"><input type="radio" name="entity_category" value="entity_private">Limited Liabiliy Partnership</label> 
				<label class="radio"><input type="radio" name="entity_category" value="entity_private">Private Limited</label> 
				<label class="radio"><input type="radio" name="entity_category" value="entity_private">Public Limited</label>
				<label class="radio"><input type="radio" name="entity_category" value="entity_private">Govt. undertaking</label> 
				<label class="radio"><input type="radio" name="entity_category" value="entity_private">Section 25 Company</label>
				<label class="radio"><input type="radio" name="entity_category" value="entity_society">Registered Society</label> 
				<label class="radio"><input type="radio" name="entity_category" value="entity_society">Trust</label>
				<label class="radio"><input type="radio" name="entity_category" value="entity_huf">HUF</label> -->
			</td>
		</tr>
		<tr>
			<td colspan="2">vii. (a) Preferred Activities:<span class="required">*</span></td>
			<td colspan="3">
				<?php 	$iec_activities_flag = false;
						if(!empty($this->iec_info['activities'])){
							$iec_activities = explode(',',$this->iec_info['activities']);	
							$iec_activities_flag = true;
						}
				?>
				<?php foreach ($this->entity_activities as $activities){
						$activity_checked = "";
						if($iec_activities_flag){
							foreach ($iec_activities as $activity){
								if ($activity == $activities['id']){
									$activity_checked =  "checked = checked";
								}
							}
						}
					?>
				<label class="checkbox"><?php echo $activities['name']?><input type="checkbox" name="entity[activities][]" value="<?php echo $activities['id']?>" <?php echo $activity_checked;?>></label> 
				<?php }?>
				<!--<label class="checkbox">Merchant Exporter<input	type="checkbox" name="exporter_type" value=""></label> 
				<label class="checkbox">Manufacturer Exporter<input type="checkbox"	name="exporter_type" value=""></label> 
				<label class="checkbox">Service Provider<input type="checkbox" name="exporter_type" value=""></label>-->
			</td>
		</tr>
		<tr>
			<td colspan="2">vii. (b) Others: (please specify)</td>
			<td colspan="3"><input class="input-xlarge" type="text" placeholder="Others" name="entity[other_activities]" id="entity_other_activities" value="<?php echo !empty($this->iec_info['other_activities'])? $this->iec_info['other_activities'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="5">viii. Bank Account Details of the Applicant's entity:</td>
		</tr>
		<tr>
			<td colspan="2">1. Name of the account holder:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Name of the account holder" name="bank[account_name]" id="bank_account_name" value="<?php echo !empty($this->iec_bank_details['account_name'])? $this->iec_bank_details['account_name'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="2">2. Account Number:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Account number" name="bank[account_number]" id="bank_account_number" value="<?php echo !empty($this->iec_bank_details['account_number'])? $this->iec_bank_details['account_number'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="2">3. Name of the Bank:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Name of the bank" name="bank[name]" id="bank_name"  value="<?php echo !empty($this->iec_bank_details['name'])? $this->iec_bank_details['name'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="2">4. Branch address of the Bank:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="Branch address of the bank" name="bank[address]" id="bank_address" value="<?php echo !empty($this->iec_bank_details['address'])? $this->iec_bank_details['address'] : ""?>"></td>
		</tr>
		<tr>
			<td colspan="2">5. IFS Code:<span class="required">*</span></td>
			<td colspan="3"><input class="input-block-level" type="text" placeholder="IFS code" name="bank[ifsc]" id="bank_ifsc"  value="<?php echo !empty($this->iec_bank_details['ifsc'])? $this->iec_bank_details['ifsc'] : ""?>"></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="375px;">Enter Registration Code:</td>
			<td><input class="input-block-level" type="text" placeholder="Registration code" name="entity[registration_code]" id="registration_code" value="<?php echo !empty($this->iec_info['registration_code'])? $this->iec_info['registration_code'] : ""?>"></td>
		</tr>
	</table>
	<!-- Branch Details -->
	<table class="table table-bordered" style="width: 950px">
		<tr class="info">
			<td colspan="5">Part B: Branch Details:</td>
		</tr>
		<tr>
			<td colspan="4">i. Enter number of Branches/Divisions/Units/Facories in India and abroad:<span class="required">*</span></td>
			
			<td style="text-align: right;">
				<!-- show the total number of branches -->
				<input class="input-block-level" type="text" placeholder="Number of branches" name="entity[total_branches]" id="branch_total" value="<?php echo !empty($this->iec_info['total_branches'])? $this->iec_info['total_branches'] : ""?>" readonly="readonly">
				<!-- existing total number of branches -->
				<input class="input-block-level" type="hidden"  name="edit_branch_total" id="edit_branch_total" value="<?php echo !empty($this->iec_info['total_branches'])? $this->iec_info['total_branches'] : ""?>" >
				<!-- for assigning the container number for the auto generated form -->
				<input class="input-block-level" type="hidden" value = "<?php echo !empty($this->iec_info['total_branches'])? $this->iec_info['total_branches']-1 : 0?>" name="branch_count" id="branch_count" >
				<button class="btn btn-mini btn-success" type="button" id="add_branch" >Add</button>
			</td>
		</tr>
		<tr>
			<td  colspan="5">
				
		<?php if(!empty($this->iec_info['total_branches'])){
				foreach($this->iec_branches as $id => $branch){
					$select_branch_id = $id;
			?>
				<div id="branch_container<?=$id?>"> 
					<table class="table table-bordered">
						<tr>
							<td rowspan="4"  width="225px">ii. Address of branches,<br /> divisions, units, <br />factories	located <br />in India and abroad:</td>
							<td colspan="1"  width="130px">Flat/Plot/Block No:<span class="required">*</span></td>
							<td colspan="3">
								<!-- <input class="input-block-level" type="hidden" name="branch[<?=$id?>][id]" value="<?php echo $branch['id']?>"> -->
								<input class="input-block-level" type="text" placeholder="Flat/Plot/Block No" name="branch[<?=$id?>][address1]" id="branch<?=$id?>_address1" value="<?php echo !empty($branch['address1'])? $branch['address1'] : ""?>">
							</td>
						</tr>
						<tr>
							<td colspan="1">Street/Area/Locality:<span class="required">*</span></td>
							<td colspan="3"><input class="input-block-level" type="text" placeholder="Street/Area/Locality" name="branch[<?=$id?>][address2]" id="branch<?=$id?>_address2" value="<?php echo !empty($branch['address2'])? $branch['address2'] : ""?>"></td>
						</tr>
						<tr>
							<td>State:<span class="required">*</span></td>
							<td>
								<select name="branch[<?=$id?>][state]" id="branch<?=$id?>_state"  class="state_selectbox">
									<option value="0">--Select--</option>
									<?php foreach ($this->states as $state){
										$state_selected_select_branch_id =  "";
										if (!empty($branch['state']) && $branch['state'] == $state['id']){
											$state_selected_select_branch_id =  "selected = selected";
										}
									?>
								  	<option value="<?php echo $state['id']?>" <?php echo $state_selected_select_branch_id;?>><?php echo $state['name']?></option>
								  	<?php }?>
								</select>
							</td>
							<td>District:<span class="required">*</span></td>
							<td>
								<select name="branch[<?=$id?>][district]" id="branch<?=$id?>_district" class="district_selectbox">
									<option value="0">--Select--</option>
									<?php foreach ($branch['districts'] as $district){
											$district_selected_select_branch_id =  "";
											if (!empty($branch['district']) && $branch['district'] == $district['id']){
												$district_selected_select_branch_id =  "selected = selected";
											}
									?>
									<option value="<?php echo $district['id']?>" <?php echo $district_selected_select_branch_id;?>><?php echo $district['name']?></option>
									<?php }?>
								</select>
							</td>	
						</tr>
						<tr>
							<td>City:<span class="required">*</span></td>
							<td>
								<select name="branch[<?=$id?>][city]" id="branch<?=$id?>_city" class="city_selectbox">
									<option value="0">--Select--</option>
									<?php foreach ($branch['cities'] as $city){
											$city_selected_select_branch_id =  "";
											if (!empty($branch['city']) && $branch['city'] == $city['id']){
												$city_selected_select_branch_id =  "selected = selected";
											}
									?>
									<option value="<?php echo $city['id']?>" <?php echo $city_selected_select_branch_id;?>><?php echo $city['name']?></option>
									<?php }?>
								</select>
							</td>
							<td>Pincode:<span class="required">*</span></td>
							<td><input class="input-block-level" type="text" placeholder="Pincode" name="branch[<?=$id?>][pincode]" id="branch<?=$id?>_pincode" value="<?php echo !empty($branch['pincode'])? $branch['pincode'] : ""?>"></td>
						</tr>
						<tr><td colspan="5" style="text-align: right;"><button class="btn btn-mini btn-danger" type="button" id="remove_branch_<?=$id?>" >Remove</button></td></tr>
					</table>
				</div>
		<?php  }}?>
				<div id="branch_details"></div>
			</td>	
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr class="info">
			<td>Part C: Please fill in the following details:</td>
		</tr>
	</table>
	<!-- Proprietorship Section -->
	<div id="firm_proprietorship"> 
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Part C1: In case the entity is a Proprietor firm:</td>
			</tr>
			<tr>
				<td colspan="2">1. a) Name of the Proprietor:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Name of the proprietor"  name="prop[name]" id="prop_name" value="<?php echo !empty($this->iec_category_details['proprietorship'][0]['name'])? $this->iec_category_details['proprietorship'][0]['name'] : ""?>"></td>
			</tr>
			<tr>
				<td rowspan="4" width="225px">b). Residential Address:</td>
				<td colspan="1"  width="130px">Flat/Plot/Block No:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Flat/Plot/Block No" name="prop[address1]" id="prop_address1" value="<?php echo !empty($this->iec_category_details['proprietorship'][0]['address1'])? $this->iec_category_details['proprietorship'][0]['address1'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="1">Street/Area/Locality:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Street/Area/Locality" name="prop[address2]" id="prop_address2" value="<?php echo !empty($this->iec_category_details['proprietorship'][0]['address2'])? $this->iec_category_details['proprietorship'][0]['address2'] : ""?>"></td>
			</tr>
			<tr>
				<td>State:<span class="required">*</span></td>
				<td>
					<select name="prop[state]" id="prop_state"  class="state_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->states as $state){
							$state_selected_prop =  "";
							if (!empty($this->iec_category_details['proprietorship'][0]['state']) && $this->iec_category_details['proprietorship'][0]['state'] == $state['id']){
								$state_selected_prop =  "selected = selected";
							}
						?>
					  	<option value="<?php echo $state['id']?>" <?php echo $state_selected_prop;?>><?php echo $state['name']?></option>
					  	<?php }?>
					</select>
				</td>
				<td>District:<span class="required">*</span></td>
				<td>
					<select name="prop[district]" id="prop_district" class="district_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->iec_category_details['proprietorship'][0]['districts'] as $district){
								$district_selected_prop =  "";
								if (!empty($this->iec_category_details['proprietorship'][0]['district']) && $this->iec_category_details['proprietorship'][0]['district'] == $district['id']){
								$district_selected_prop =  "selected = selected";
							}
						?>
						<option value="<?php echo $district['id']?>" <?php echo $district_selected_prop;?>><?php echo $district['name']?></option>
						<?php }?>
					</select>
				</td>
			</tr>
			<tr>
				<td>City:<span class="required">*</span></td>
				<td>
					<select name="prop[city]" id="prop_city" class="city_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->iec_category_details['proprietorship'][0]['cities'] as $city){
								$city_selected_prop =  "";
								if (!empty($this->iec_category_details['proprietorship'][0]['city']) && $this->iec_category_details['proprietorship'][0]['city'] == $city['id']){
								$city_selected_prop =  "selected = selected";
							}
						?>
						<option value="<?php echo $city['id']?>" <?php echo $city_selected_prop;?>><?php echo $city['name']?></option>
						<?php }?>
					</select>
				</td>
				<td>Pincode:<span class="required">*</span></td>
				<td><input class="input-block-level" type="text" placeholder="Pincode" name="prop[pincode]" id="prop_pincode" value="<?php echo !empty($this->iec_category_details['proprietorship'][0]['pincode'])? $this->iec_category_details['proprietorship'][0]['pincode'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">c) Aadhaar Card Number, if available:</td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Aadhaar card number" name="prop[aadhaar_number]" id="prop_aadharno" value="<?php echo !empty($this->iec_category_details['proprietorship'][0]['aadhaar_number'])? $this->iec_category_details['proprietorship'][0]['aadhaar_number'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<!-- Partnership Section -->
	<div id="firm_partnership">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Part C2: In case he entity is a Partnership firm:</td>
			</tr>
			<tr>
				<td colspan="1" rowspan="3" >1. PAN details in the entity:</td>
				<td colspan="2" width="300px">Name as in PAN:<span class="required">*</span></td>
				<td colspan="2" width="300px;"><input class="input-block-level" type="text"	placeholder="Name as in PAN" name="entity_partnership[pan_name_entity]" id="partner_pan_name_entity" value="<?php echo !empty($this->iec_info['pan_name_entity'])? $this->iec_info['pan_name_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">Date of Incorporation (DD/MM/YYYY):<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Date of incorporation" name="entity_partnership[incorporation_date]" id="partner_incorporation_date" value="<?php echo !empty($this->iec_info['incorporation_date'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['incorporation_date']}")->format('d/m/Y') : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">PAN:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="PAN" name="entity_partnership[pan_entity]" id="partner_pan_entity" value="<?php echo !empty($this->iec_info['pan_entity'])? $this->iec_info['pan_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">2. Enter the number of partners in the Partnership Firm:<span class="required">*</span></td>
				<td colspan="3" style="text-align: right;">
					<!-- show the total number of partners -->
					<input class="input-block-level" type="text" placeholder="Number of partners" name="entity_partnership[total_partners]" id="partner_total" value="<?php echo !empty($this->iec_info['total_partners'])? $this->iec_info['total_partners'] : ""?>" readonly="readonly">
					<!-- existing total number of partners -->
					<input class="input-block-level" type="hidden"  name="edit_partner_total" id="edit_partner_total" value="<?php echo !empty($this->iec_info['total_partners'])? $this->iec_info['total_partners'] : ""?>" >
					<!-- for assigning the container number for the auto generated partners -->
					<input class="input-block-level" type="hidden" value = "<?php echo !empty($this->iec_info['total_partners'])? $this->iec_info['total_partners']-1 : 0?>" name="partner_count" id="partner_count" >
					<button class="btn btn-mini btn-success" type="button" id="add_partner" >Add</button>
				
				</td>	
			</tr>
			<tr>
				<td colspan="5">3. Fill the following details for each partner: </td>
			</tr>
			<tr>
				<td  colspan="5">
				<?php if(!empty($this->iec_info['total_partners'])){
				foreach($this->iec_category_details['partnership'] as $id => $partner){
					$select_id = $id;
				?>
					<div id="partner_container<?=$id?>"> 
						<table class="table table-bordered" >
							<tr>
								<td colspan="2">a. Name as in PAN:<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Name as in PAN" name="entity_partnership[partners][<?=$id?>][name]" id="partner<?=$id?>_name" value="<?php echo !empty($partner['name'])? $partner['name'] : ""?>"></td>
							</tr>
							<tr>
								<td colspan="2">b. Father's Name:<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Father's name" name="entity_partnership[partners][<?=$id?>][surname]" id="partner<?=$id?>_surname" value="<?php echo !empty($partner['surname'])? $partner['surname'] : ""?>"></td>
							</tr>
							<tr>
								<td colspan="2">c. Date of Birth (DD/MM/YYYY):<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Date of birth" name="entity_partnership[partners][<?=$id?>][dob]" id="partner<?=$id?>_dob" value="<?php echo !empty($partner['dob'])? DateTime::createFromFormat("Y-m-d", "{$partner['dob']}")->format('d/m/Y') : ""?>"></td>
							</tr>
							<tr>
								<td rowspan="4" width="225px">d. Residential Address:
								</td>
								<td colspan="1"  width="130px">Flat/Plot/Block No:<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Flat/Plot/Block No" name="entity_partnership[partners][<?=$id?>][address1]" id="partner<?=$id?>_address1" value="<?php echo !empty($partner['address1'])? $partner['address1']: ""?>"></td>
							</tr>
							<tr>
								<td colspan="1">Street/Area/Locality:<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Street/Area/Locality" name="entity_partnership[partners][<?=$id?>][address2]" id="partner<?=$id?>_address2" value="<?php echo !empty($partner['address2'])? $partner['address2']: ""?>"></td>
							</tr>
							<tr>
								<td>State:<span class="required">*</span></td>
								<td>
									<select name="entity_partnership[partners][<?=$id?>][state]" id="partner<?=$id?>_state"  class="state_selectbox">
										<option value="0">--Select--</option>
										<?php foreach ($this->states as $state){
											$state_selected_partner_select_id =  "";
											if (!empty($partner['state']) && $partner['state'] == $state['id']){
												$state_selected_partner_select_id =  "selected = selected";
											}
										?>
									  	<option value="<?php echo $state['id']?>" <?php echo $state_selected_partner_select_id;?>><?php echo $state['name']?></option>
									  	<?php }?>
									</select>
								</td>
								<td>District:<span class="required">*</span></td>
								<td>
									<select name="entity_partnership[partners][<?=$id?>][district]" id="partner<?=$id?>_district" class="district_selectbox">
										<option value="0">--Select--</option>
										<?php foreach ($partner['districts'] as $district){
												$district_selected_partner_select_id =  "";
												if (!empty($partner['district']) && $partner['district'] == $district['id']){
													$district_selected_partner_select_id =  "selected = selected";
												}
										?>
										<option value="<?php echo $district['id']?>" <?php echo $district_selected_partner_select_id;?>><?php echo $district['name']?></option>
										<?php }?>
									</select>
								</td>
							</tr>
							<tr>
								<td>City:<span class="required">*</span></td>
								<td>
									<select name="entity_partnership[partners][<?=$id?>][city]" id="partner<?=$id?>_city" class="city_selectbox">
										<option value="0">--Select--</option>
										<?php foreach ($partner['cities'] as $city){
												$district_selected_partner_select_id =  "";
												if (!empty($partner['city']) && $partner['city'] == $city['id']){
													$district_selected_partner_select_id =  "selected = selected";
												}
										?>
										<option value="<?php echo $city['id']?>" <?php echo $district_selected_partner_select_id;?>><?php echo $city['name']?></option>
										<?php }?>
									</select>
								</td>
								<td>Pincode:<span class="required">*</span></td>
								<td><input class="input-block-level" type="text" placeholder="Pincode" name="entity_partnership[partners][<?=$id?>][pincode]" id="partner<?=$id?>_pincode" value="<?php echo !empty($partner['pincode'])? $partner['pincode']: ""?>"></td>
							</tr>
							<tr>
								<td colspan="2">e. Mobile No:<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Mobile no" name="entity_partnership[partners][<?=$id?>][mobile]" id="partner<?=$id?>_mobile" value="<?php echo !empty($partner['mobile'])? $partner['mobile']: ""?>"></td>
							</tr>
							<tr>
								<td colspan="2">f. PAN:<span class="required">*</span></td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="PAN" name="entity_partnership[partners][<?=$id?>][pan]" id="partner<?=$id?>_pan" value="<?php echo !empty($partner['pan'])? $partner['pan']: ""?>"></td>
							</tr>
							<tr>
								<td colspan="2">g. Aadhaar Card Number, if available:</td>
								<td colspan="3"><input class="input-block-level" type="text" placeholder="Aadhaar card number" name="entity_partnership[partners][<?=$id?>][aadhaar_number]" id="partner<?=$id?>_aadhaarno" value="<?php echo !empty($partner['aadhaar_number'])? $partner['aadhaar_number']: ""?>"></td>
							</tr>
							<tr><td colspan="5" style="text-align: right;"><button class="btn btn-mini btn-danger" type="button" id="remove_partner_<?=$id?>" >Remove</button></td></tr>
						</table>
					</div>
					<?php }}?>
					<div id="partner_details"></div>
				</td>	
			</tr>	
		</table>
	</div>
	<!--Private Ltd Section -->
	<div id="firm_privateltd">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5" >Part C3: In case the entity is a Limited liability Partnership/Private/Public/Govt.Underaking/Secion 25 Company:</td>
			</tr>
			<tr>
				<td rowspan="3">1. PAN details of the firm:</td>
				<td colspan="2" >Name as in PAN:<span class="required">*</span></td>
				<td colspan="2" width="300px;"><input class="input-block-level" type="text" placeholder="Name as in PAN" name="entity_privateltd[pan_name_entity]" id="privateltd_pan_name_entity" value="<?php echo !empty($this->iec_info['pan_name_entity'])? $this->iec_info['pan_name_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">Date of Incorporation(DD/MM/YYYY):<span class="required">*</span></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Date of incorporation"  name="entity_privateltd[incorporation_date]" id="privateltd_incorporation_date" value="<?php echo !empty($this->iec_info['incorporation_date'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['incorporation_date']}")->format('d/m/Y') : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">PAN:<span class="required">*</span></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="PAN" name="entity_privateltd[pan_entity]" id="privateltd_pan_entity" value="<?php echo !empty($this->iec_info['pan_entity'])? $this->iec_info['pan_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">2. LLPIN/CIN(Whichever is applicable):</td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="LLPIN/CIN" name="entity_privateltd[llpin_cin]" id="privateltd_llpin_cin" value="<?php echo !empty($this->iec_info['llpin_cin'])? $this->iec_info['llpin_cin'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">3. Registration Cerification No:</td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Registration cerification no" name="entity_privateltd[registration_cert_number]" id="privateltd_registration_cert_number" value="<?php echo !empty($this->iec_info['registration_cert_number'])? $this->iec_info['registration_cert_number'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">4. Enter the number of Partners/Director in the Firm/Company:<span class="required">*</span></td>
				<td colspan="3"  style="text-align: right;">
					<!-- show the total number of partners -->
					<input class="input-block-level" type="text" placeholder="Number of partners" name="entity_privateltd[total_partners]" id="privateltd_total" value="<?php echo !empty($this->iec_info['total_partners'])? $this->iec_info['total_partners'] : ""?>" readonly="readonly">
					<!-- existing total number of partners -->
					<input class="input-block-level" type="hidden"  name="edit_privateltd_total" id="edit_privateltd_total" value="<?php echo !empty($this->iec_info['total_partners'])? $this->iec_info['total_partners'] : ""?>" >
					<!-- for assigning the container number for the auto generated partners -->
					<input class="input-block-level" type="hidden" value = "<?php echo !empty($this->iec_info['total_partners'])? $this->iec_info['total_partners']-1 : 0?>" name="privateltd_count" id="privateltd_count" >
					<button class="btn btn-mini btn-success" type="button" id="add_privateltd" >Add</button>
					
				</td>
			</tr>
			<tr>
				<td colspan="5">5. Fill in the following details for each Partner/Director:</td>
			</tr>
			<tr> 
				<td colspan="5">
					<?php if(!empty($this->iec_info['total_partners'])){
							foreach($this->iec_category_details['privateltd'] as $id => $privateltd){
								$select_id = $id;
								$default_privateltd_display = "style='display:none'";
					?>
					<div id="privateltd_container<?=$id?>"> 
						<table  class="table table-bordered">
							<tr>
								<td width="285px;">a. Name:<span class="required">*</span></td>
								<td>
									<!-- <input class="input-block-level" type="hidden" name="entity_privateltd[partners][<?=$id?>][id]" value="<?php echo $branch['id']?>"> -->
									<input class="input-block-level" type="text" placeholder="Name of the partner/director" name="entity_privateltd[partners][<?=$id?>][name]" id="privateltd<?=$id?>_name" value="<?php echo !empty($privateltd['name'])? $privateltd['name'] : ""?>">
								</td>
							</tr>
							<tr>
								<td>b. PAN:<span class="required">*</span></td>
								<td><input class="input-block-level" type="text" placeholder="PAN" name="entity_privateltd[partners][<?=$id?>][pan]" id="privateltd<?=$id?>_pan" value="<?php echo !empty($privateltd['pan'])? $privateltd['pan'] : ""?>"></td>
							</tr>
							<tr>
								<td>c. Director Identity Number:<span class="required">*</span></td>
								<td><input class="input-block-level" type="text" placeholder="Director identity number"  name="entity_privateltd[partners][<?=$id?>][director_id_number]" id="privateltd<?=$id?>_director_id" value="<?php echo !empty($privateltd['director_id_number'])? $privateltd['director_id_number'] : ""?>"></td>
							</tr>
							<tr>
								<td >d. Aadhaar Card Number, if available:</td>
								<td ><input class="input-block-level" type="text" placeholder="Aadhaar card number" name="entity_privateltd[partners][<?=$id?>][aadhaar_number]" id="privateltd<?=$id?>_aadhaarno" value="<?php echo !empty($privateltd['aadhaar_number'])? $privateltd['aadhaar_number'] : ""?>"></td>
							</tr>
							<tr><td colspan="5" style="text-align: right;"><button class="btn btn-mini btn-danger" type="button" id="remove_privateltd_<?=$id?>" >Remove</button></td></tr>
						</table>
					</div>
					<?php }}?>
					<div id="privateltd_details"></div>
				</td>
			</tr>
		</table>
	</div>
	<!-- Society Section -->
	<div id="firm_society">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Part C4: In case the enity is a Registred Society/Trust**:</td>
			</tr>
			<tr>
				<td rowspan="3">1. PAN details of the <br/>Society/Trust:</td>
				<td colspan="2">Name as in PAN:<span class="required">*</span></td>
				<td colspan="2" width="300px"><input class="input-block-level" type="text" placeholder="Name as in PAN" name="entity_society[pan_name_entity]" id="society_pan_name_entity" value="<?php echo !empty($this->iec_info['pan_name_entity'])? $this->iec_info['pan_name_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">Date of Incorporation(DD/MM/YYYY):<span class="required">*</span></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Date of incorporation" name="entity_society[incorporation_date]" id="society_incorporation_date" value="<?php echo !empty($this->iec_info['incorporation_date'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['incorporation_date']}")->format('d/m/Y') : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">PAN:<span class="required">*</span></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="PAN" name="entity_society[pan_entity]" id="society_pan_entity" value="<?php echo !empty($this->iec_info['pan_entity'])? $this->iec_info['pan_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">2. Registration Number:</td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Registration number" name="entity_society[registration_cert_number]" id="society_registration_number" value="<?php echo !empty($this->iec_info['registration_cert_number'])? $this->iec_info['registration_cert_number'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="5">3. Details of the Secretary/Cheif executive of the Society; or Managing Trustee of the Trust:</td>
			</tr>
			<tr>
				<td colspan="2">a. Name as in PAN:<span class="required">*</span></td>
				<td colspan="3" ><input class="input-block-level" type="text" placeholder="Name as in PAN" name="entity_society[trustee][name]" id="society_name" value="<?php echo !empty($this->iec_category_details['society'][0]['name'])? $this->iec_category_details['society'][0]['name'] : ""?>"></td>
			</tr>
			<tr>
				<td rowspan="4" width="225px">b. Residential Address:
				</td>
				<td colspan="1"  width="130px">Flat/Plot/Block No:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Flat/Plot/Block No" name="entity_society[trustee][address1]" id="society_address1" value="<?php echo !empty($this->iec_category_details['society'][0]['address1'])? $this->iec_category_details['society'][0]['address1'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="1">Street/Area/Locality:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Street/Area/Locality" name="entity_society[trustee][address2]" id="society_address2" value="<?php echo !empty($this->iec_category_details['society'][0]['address2'])? $this->iec_category_details['society'][0]['address2'] : ""?>"></td>
			</tr>
			<tr>
				<td>State:<span class="required">*</span></td>
				<td>
					<select name="entity_society[trustee][state]" id="society_state"  class="state_selectbox">
						<option value="0">--Select--</option>
					  	<?php foreach ($this->states as $state){
							$state_selected_society =  "";
							if (!empty($this->iec_category_details['society'][0]['state']) && $this->iec_category_details['society'][0]['state'] == $state['id']){
								$state_selected_society =  "selected = selected";
							}
						?>
					  	<option value="<?php echo $state['id']?>" <?php echo $state_selected_society;?>><?php echo $state['name']?></option>
					  	<?php }?>
					</select>
				</td>
				<td>District:<span class="required">*</span></td>
				<td>
					<select name="entity_society[trustee][district]" id="society_district" class="district_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->iec_category_details['society'][0]['districts'] as $district){
								$district_selected_society =  "";
								if (!empty($this->iec_category_details['society'][0]['district']) && $this->iec_category_details['society'][0]['district'] == $district['id']){
									$district_selected_society =  "selected = selected";
								}
						?>
						<option value="<?php echo $district['id']?>" <?php echo $district_selected_society;?>><?php echo $district['name']?></option>
						<?php }?>
					</select>
				</td>
			</tr>
			<tr>
				<td>City:<span class="required">*</span></td>
				<td>
					<select name="entity_society[trustee][city]" id="society_city" class="city_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->iec_category_details['society'][0]['cities'] as $city){
								$city_selected_society =  "";
								if (!empty($this->iec_category_details['society'][0]['city']) && $this->iec_category_details['society'][0]['city'] == $city['id']){
								$city_selected_society =  "selected = selected";
							}
						?>
						<option value="<?php echo $city['id']?>" <?php echo $city_selected_society;?>><?php echo $city['name']?></option>
						<?php }?>
					</select>
				</td>
				<td>Pincode:<span class="required">*</span></td>
				<td><input class="input-block-level" type="text" placeholder="Pincode" name="entity_society[trustee][pincode]" id="society_pincode" value="<?php echo !empty($this->iec_category_details['society'][0]['pincode'])? $this->iec_category_details['society'][0]['pincode'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">c. Aadhar Card Number(if available):</td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Aadhar card number" name="entity_society[trustee][aadhaar_number]" id="society_aadhaarno" value="<?php echo !empty($this->iec_category_details['society'][0]['aadhaar_number'])? $this->iec_category_details['society'][0]['aadhaar_number'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<!-- HUF section -->
	<div id="firm_huf">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Part C5: In case the enity is a HUF:</td>
			</tr>
			<tr>
				<td rowspan="3">1. PAN deails of the Entity:</td>
				<td colspan="2">Name as in PAN:<span class="required">*</span></td>
				<td colspan="2" width="300px"><input class="input-block-level" type="text" placeholder="Name as in PAN" name="entity_huf[pan_name_entity]" id="huf_pan_name_entity" value="<?php echo !empty($this->iec_info['pan_name_entity'])? $this->iec_info['pan_name_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">Date of Incorporation(DD/MM/YYYY):<span class="required">*</span></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Date of incorporation" name="entity_huf[incorporation_date]" id="huf_incorporation_date" value="<?php echo !empty($this->iec_info['incorporation_date'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['incorporation_date']}")->format('d/m/Y') : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">PAN:<span class="required">*</span></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="PAN" name="entity_huf[pan_entity]" id="huf_pan_entity" value="<?php echo !empty($this->iec_info['pan_entity'])? $this->iec_info['pan_entity'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="5">2. Details of Karta:</td>
			</tr>
				<tr>
				<td colspan="2">a. Name as in PAN:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Name as in PAN" name="entity_huf[karta][name]" id="huf_name" value="<?php echo !empty($this->iec_category_details['huf'][0]['name'])? $this->iec_category_details['huf'][0]['name'] : ""?>"></td>
			</tr>
			<tr>
				<td rowspan="4" width="225px">b. Residential Address
				</td>
				<td colspan="1"  width="130px">Flat/Plot/Block No:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Flat/Plot/Block No" name="entity_huf[karta][address1]" id="huf_address1" value="<?php echo !empty($this->iec_category_details['huf'][0]['address1'])? $this->iec_category_details['huf'][0]['address1'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="1">Street/Area/Locality:<span class="required">*</span></td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Street/Area/Locality" name="entity_huf[karta][address2]" id="huf_address2" value="<?php echo !empty($this->iec_category_details['huf'][0]['address2'])? $this->iec_category_details['huf'][0]['address2'] : ""?>"></td>
			</tr>
			<tr>
				<td>State:<span class="required">*</span></td>
				<td>
					<select name="entity_huf[karta][state]" id="huf_state"  class="state_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->states as $state){
							$state_selected_huf =  "";
							if (!empty($this->iec_category_details['huf'][0]['state']) && $this->iec_category_details['huf'][0]['state'] == $state['id']){
								$state_selected_huf =  "selected = selected";
							}
						?>
					  	<option value="<?php echo $state['id']?>" <?php echo $state_selected_huf;?>><?php echo $state['name']?></option>
					  	<?php }?>
					</select>
				</td>
				<td>District:<span class="required">*</span></td>
				<td>
					<select name="entity_huf[karta][district]" id="huf_district" class="district_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->iec_category_details['huf'][0]['districts'] as $district){
								$district_selected_huf =  "";
								if (!empty($this->iec_category_details['huf'][0]['district']) && $this->iec_category_details['huf'][0]['district'] == $district['id']){
									$district_selected_huf =  "selected = selected";
								}
						?>
						<option value="<?php echo $district['id']?>" <?php echo $district_selected_huf;?>><?php echo $district['name']?></option>
						<?php }?>
					</select>
				</td>
			</tr>
			<tr>
				<td>City:<span class="required">*</span></td>
				<td>
					<select name="entity_huf[karta][city]" id="huf_city" class="city_selectbox">
						<option value="0">--Select--</option>
						<?php foreach ($this->iec_category_details['huf'][0]['cities'] as $city){
								$city_selected_huf =  "";
								if (!empty($this->iec_category_details['huf'][0]['city']) && $this->iec_category_details['huf'][0]['city'] == $city['id']){
								$city_selected_huf =  "selected = selected";
							}
						?>
						<option value="<?php echo $city['id']?>" <?php echo $city_selected_huf;?>><?php echo $city['name']?></option>
						<?php }?>
					</select>
				</td>
				<td>Pincode:<span class="required">*</span></td>
				<td><input class="input-block-level" type="text" placeholder="Pincode" name="entity_huf[karta][pincode]" id="huf_pincode" value="<?php echo !empty($this->iec_category_details['huf'][0]['pincode'])? $this->iec_category_details['huf'][0]['pincode'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="2">3. Aadhaar Card Details, if available:</td>
				<td colspan="3"><input class="input-block-level" type="text" placeholder="Aadhaar card details" name="entity_huf[karta][aadhaar_number]" id="huf_aadhaar_number" value="<?php echo !empty($this->iec_category_details['huf'][0]['aadhaar_number'])? $this->iec_category_details['huf'][0]['aadhaar_number'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<div id="ind_reg_details">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Industrial Registration Details</td>
			</tr>
			<tr>
				<td colspan="1">1. SSI/IEM/LOI or IL Registration No/any other to prove a manufacturer status:</td>
				<td colspan="4"><input class="input-block-level" type="text" placeholder="Registration No" name="entity[imr_reg_num]" id="imr_reg_num" value="<?php echo !empty($this->iec_info['imr_reg_num'])? $this->iec_info['imr_reg_num'] : ""?>"></td>
			</tr>
			<tr>
				<td rowspan="2">2. Date of issue and Validity / Issuing Authority</td>
				<td colspan="2">
				From:<span class="required">*</span>
					<input class="input-block-level" type="text" placeholder="From Date" name="entity[imr_doi]" id="imr_doi" value="<?php echo !empty($this->iec_info['imr_doi'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['imr_doi']}")->format('d/m/Y') : ""?>"></td>
				<td colspan="2">To:<span class="required">*</span>
					<input class="input-block-level" type="text" placeholder="To Date" name="entity[imr_validity]" id="imr_validity" value="<?php echo !empty($this->iec_info['imr_validity'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['imr_validity']}")->format('d/m/Y') : ""?>"></td>
			</tr>
			<tr><td colspan="4"><input class="input-block-level" type="text" placeholder="Issuing Authority" name="entity[imr_ia]" id="imr_ia" value="<?php echo !empty($this->iec_info['imr_ia'])? $this->iec_info['imr_ia'] : ""?>"></td></tr>
				
			<tr>
				<td colspan="1">3. Products for which registered</td>
				<td colspan="4" ><input class="input-block-level" type="text" placeholder="Registered Products" name="entity[imr_reg_prods]" id="imr_reg_prods" value="<?php echo !empty($this->iec_info['imr_reg_prods'])? $this->iec_info['imr_reg_prods'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<div id="ser_tax_reg_details">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Service Tax Registration Details (in case of Service providers)</td>
			</tr>
			<tr>
				<td colspan="1">1. Service Tax Registration No / Issuing Authority</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Registration No" name="entity[str_reg_num]" id="str_reg_num" value="<?php echo !empty($this->iec_info['str_reg_num'])? $this->iec_info['str_reg_num'] : ""?>"></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Issuing Authority" name="entity[str_ia]" id="str_ia" value="<?php echo !empty($this->iec_info['str_ia'])? $this->iec_info['str_ia'] : ""?>">
				</td>
			</tr>
			<tr>
				<td colspan="1">2. Services for which registered</td>
				<td colspan="4"><input class="input-block-level" type="text" placeholder="Registered Services" name="entity[str_reg_items]" id="str_reg_items" value="<?php echo !empty($this->iec_info['str_reg_items'])? $this->iec_info['str_reg_items'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<div id="rcmc_details">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">RCMC Details</td>
			</tr>
			<tr>
				<td colspan="1">1. RCMC No / Issuing Authority</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="RCMC No" name="entity[rcmc_num]" id="rcmc_num" value="<?php echo !empty($this->iec_info['rcmc_num'])? $this->iec_info['rcmc_num'] : ""?>"></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Issuing Authority" name="entity[rcmc_ia]" id="rcmc_ia" value="<?php echo !empty($this->iec_info['rcmc_ia'])? $this->iec_info['rcmc_ia'] : ""?>">
				</td>
			</tr>
			<tr>
				<td colspan="1">2. Date of issue and Validity:</td>
				<td colspan="2">From:<span class="required">*</span><input class="input-block-level" type="text" placeholder="From date" name="entity[rcmc_doi]" id="rcmc_doi" value="<?php echo !empty($this->iec_info['rcmc_doi'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['rcmc_doi']}")->format('d/m/Y') : ""?>"></td>
				<td colspan="2">To:<span class="required">*</span><input class="input-block-level" type="text" placeholder="To Date" name="entity[rcmc_validity]" id="rcmc_validity" value="<?php echo !empty($this->iec_info['rcmc_validity'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['rcmc_validity']}")->format('d/m/Y') : ""?>"></td>
			</tr>
			<tr>
				<td colspan="1">3. Products for which registered</td>
				<td colspan="4" ><input class="input-block-level" type="text" placeholder="Registered Products" name="entity[rcmc_reg_prods]" id="rcmc_reg_prods" value="<?php echo !empty($this->iec_info['rcmc_reg_prods'])? $this->iec_info['rcmc_reg_prods'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<div id="stat_house_details">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="2">Status House Details(Please select)
				<td colspan="3"><input type="text" class="rb-rating" name="entity[shd_rating]" id="shd_rating" value="0" value="<?php echo !empty($this->iec_info['shd_rating'])? $this->iec_info['shd_rating'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="1">1. Certificate number / Issuing Authority:</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Certificate number" name="entity[shd_cert_num]" id="shd_cert_num" value="<?php echo !empty($this->iec_info['shd_cert_num'])? $this->iec_info['shd_cert_num'] : ""?>"></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Issuing Authority" name="entity[shd_ia]" id="shd_ia" value="<?php echo !empty($this->iec_info['shd_ia'])? $this->iec_info['shd_ia'] : ""?>">
				</td>
			</tr>
			<tr>
				<td colspan="1">2. Date of issue and Validity:</td>
				<td colspan="2">From:<span class="required">*</span><input class="input-block-level" type="text" placeholder="From date" name="entity[shd_doi]" id="shd_doi" value="<?php echo !empty($this->iec_info['shd_doi'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['shd_doi']}")->format('d/m/Y') : ""?>"></td>
				<td colspan="2">To:<span class="required">*</span><input class="input-block-level" type="text" placeholder="To Date" name="entity[shd_validity]" id="shd_validity" value="<?php echo !empty($this->iec_info['shd_validity'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['shd_validity']}")->format('d/m/Y') : ""?>"></td>
			</tr>
		</table>	
	</div>
	<div id="cent_exc_details">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">Central Excise Registration Details</td>
			</tr>
			<tr>
				<td colspan="1">Central Excise Registration No./ Issuing Authority</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Registration number" name="entity[cer_reg_num]" id="cer_reg_num" value="<?php echo !empty($this->iec_info['cer_reg_num'])? $this->iec_info['cer_reg_num'] : ""?>"></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Issuing Authority" name="entity[cer_ia]" id="cer_ia" value="<?php echo !empty($this->iec_info['cer_ia'])? $this->iec_info['cer_ia'] : ""?>"></td>
			</tr>
			<tr>
				<td colspan="1">Date of registration</td><td colspan="4"><input class="input-medium" type="text" placeholder="Date of Registration" name="entity[cer_reg_date]" id="cer_reg_date" value="<?php echo !empty($this->iec_info['cer_reg_date'])? DateTime::createFromFormat("Y-m-d", "{$this->iec_info['cer_reg_date']}")->format('d/m/Y') : ""?>"></td>
			</tr>
		</table>
	</div>
	<div id="cent_exc_details">
		<table class="table table-bordered" style="width: 950px">
			<tr class="info">
				<td colspan="5">VAT Registration Details</td>
			</tr>
			<tr>
				<td colspan="1">VAT Registration No./ Issuing Authority</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Registration number" name="entity[vat_reg_num]" id="vat_reg_num" value="<?php echo !empty($this->iec_info['vat_reg_num'])? $this->iec_info['vat_reg_num'] : ""?>"></td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="Issuing Authority" name="entity[vat_ia]" id="vat_ia" value="<?php echo !empty($this->iec_info['vat_ia'])? $this->iec_info['vat_ia'] : ""?>"></td>
			</tr>
		</table>
	</div>
	<!-- Turnover Details Section -->
	<div id="financial_details">
		<input class="input-block-level" type="hidden" value = "<?php echo count($this->iec_turnover_details)?>" name="finance_row_count" id="finance_row_count" >
		<table class="table table-bordered" style="width: 950px" id="finance_data">
			<tr class="info">
				<td colspan="5">Turnover Details for the preceeding three final years: </td>
			</tr>
			<tr>
				<td colspan="1">Financial Year</td>
				<td colspan="2">Annual Domestic Turnover(Rs.Lakhs)</td>
				<td colspan="2">Annual Export Turnover(Rs.Lakhs)</td>
				
			</tr>
			<?php  
				foreach ($this->iec_turnover_details as $to_id => $turnover_details){
			?>
			<tr id="turnover_details<?php echo $to_id?>">
				<td colspan="1" width="225px">
					<!-- <input class="input-block-level" type="hidden" value = "<?php echo $turnover_details['id']; ?>" name="turnover_details[<?php echo $to_id?>][id]"> -->
					<select name="turnover_details[<?php echo $to_id?>][financial_year]" id="financial_year<?php echo $to_id?>">
						<?php foreach ($this->financial_years as $financial_year){
							$financial_year_selected =  "";
							if (!empty($turnover_details['financial_year']) && $turnover_details['financial_year'] == $financial_year){
								$financial_year_selected =  "selected = selected";
							}
						?>
					  	<option value="<?php echo $financial_year;?>" <?php echo $financial_year_selected;?>><?php echo $financial_year;?></option>
					  	<?php }?>
					</select>
				</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="" name="turnover_details[<?php echo $to_id?>][domestic_turnover]" id="domestic_turnover_<?php echo $to_id?>" value="<?php echo $turnover_details['domestic_turnover']; ?>"></td>
				<td colspan="1"><input class="input-block-level" type="text" placeholder="" name="turnover_details[<?php echo $to_id?>][export_turnover]" id="export_turnover_<?php echo $to_id?>" value="<?php echo $turnover_details['export_turnover'];?>"></td>
				<td colspan="1"><a href="javascript:void(0);" onclick="addMoreRows(this.form);"><i class="icon-plus"></i></a></td>
			</tr>
			<?php $to_id++; }	?>
			<!--  
			<tr id="rowCount<?php echo $to_id;?>">	
				<td colspan="1">
					<select name="turnover_details[<?php echo $to_id;?>][financial_year]" id="financial_year_<?php echo $to_id;?>" ></select>
				</td>
				<td colspan="2"><input class="input-block-level" type="text" placeholder="" name="turnover_details[<?php echo $to_id;?>][domestic_turnover]" id="domestic_turnover_<?php echo $to_id;?>"></td>
				<td colspan="1"><input class="input-block-level" type="text" placeholder="" name="turnover_details[<?php echo $to_id;?>][export_turnover]" id="export_turnover_<?php echo $to_id;?>"></td>
				<td colspan="1"><a href="javascript:void(0);" onclick="addMoreRows(this.form);"><i class="icon-plus"></i></a></td>
			</tr>
			-->
		</table>
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr class="info">
			<td colspan="2">Part D: Declaration/Undertaking:</td>
		</tr>
		<tr>
			<td>1</td>
			<td>
				I/We hereby certify that: <br/>
				A. the entity for whom the appliction has been made have not been penalized under any of the following Acts (as amended from time to time):<br/>
				(i)   The customes Act, 1962,<br/>
				(ii)  The Central Excise Act 1944,<br/>
				(iii) Foreign Trade (Development &amp; Regulation) Act 1992, and<br/>
				(iv)  The Foreign Exchange Management Act, 1999 <br/>
				(v)   The Conservaion of Foreign Exchange, Prevention of Smuggling Acivities Act, 1974<br/>
				B. None of the Directors/Partners/Proprietor/Karta/Trustees of the company/firm/HUF/Trust, (as he case may be), is/are a Director(s)/Partner(s)/Proprietor/Karta/Trustee in any oher Company/firm/entity which is on the Denied Entity List<br/>
				C. neither the Registered Office of the company/Head Office of the firm / nor any of its Branch Office(s)/Unit(s)/Division(s) has been declared a defaulter as has otherwise been made ineligible for undertaking import/export under any of the provisions of the policy <br/>
				D. we have not obained not applied for issuance of an Importer Exporter Code Number in the name of our Registered/Head Office o any oher Licensing Authority
			</td>
		</tr>
		<tr>
			<td>2</td>
			<td>
				I/We undertake to abide by he provisions f the Foreign Trade (Development and Regulation) Ac, 1992, as amended from time to time, the Rule and Orders framed here under, the Foreign Trade Policy, the handbook of Procedured as the ITC(HS) Classificaion of Export &amp; Import Items<br/>
			</td>
		</tr>
		<tr>
			<td>3</td>
			<td>
				I/We fully undersand that if any information furnished in the applicaion is found incorrect or false will render me/us liable for any penal action or other consequences as many be prescribed in law or otherwise warrented.<br/>
			</td>
		</tr>
		<tr>
			<td>4</td>
			<td>
				I/We hereby declare that he particulars and the saements made in this application are true and correct to the best of my/our knowledge and belief and nothing has been concealed or withheld there from<br/>
			</td>
		</tr>
		<tr>
			<td>5</td>
			<td>
				I hereby certify that I am authorized to verify ans sign this declaration as per Paragraph 9.06 of the Foreign Trade policy
			</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>
				<label class="checkbox"><input type="checkbox" name="entity[proof_of_accept]"  id="proof_of_accept">Tick the box as acceptance of declaraion/undertaking.</label>
			</td>
		</tr>
	</table>
	<div style="text-align: center;">
		<button type="submit" class="btn btn-primary" name="submitform" value="Submit Form" id="submit_iecform">Submit</button> 
		<?php if(!empty($this->iec_info['status']) &&  $this->iec_info['status'] == '6'){?>
		<span style="padding-right: 25px"> </span>
		<button type="submit" class="btn btn-warning" name="saveform" value="Save Form"  id="save_iecform">Save</button>
		<?php }?>
		<span style="padding-right: 25px"></span> 
		<button type="reset" class="btn btn-danger">Reset</button>
		<span style="padding-right: 25px"></span> 
		<a href="iec/index" type="button" class="btn btn-inverse">Back</a>
		<!-- 
		<span style="padding-right: 25px"></span> 
		<a href="#" type="button" class="btn btn-warning">Print</a>
		 -->
	</div>
</form>
<script>
$(function(){
    var hasBeenTrigged = false;
    var target = $("#categories_section_select_check").offset().top;
    $(window).scroll(function() {
        if ($(this).scrollTop() >= target && !hasBeenTrigged) { // if scroll is greater/equal then 100 and hasBeenTrigged is set to false.
        	if(!$('input[name="entity[category]"]:checked').val()){
    			bootbox.alert("Please select the nature of concern/entity before proceeding.",function() {
    				$("html, body").animate({ scrollTop: target }, "slow");
    			});
    		}
            hasBeenTrigged = true;
        }
    });

    $('#partner_incorporation_date').datepicker({format: "dd/mm/yyyy"});
    $('#privateltd_incorporation_date').datepicker({format: "dd/mm/yyyy"});
    $('#society_incorporation_date').datepicker({format: "dd/mm/yyyy"});
    $('#huf_incorporation_date').datepicker({format: "dd/mm/yyyy"});
    $('#imr_doi').datepicker({format: "dd/mm/yyyy"});
	$('#imr_validity').datepicker({format: "dd/mm/yyyy"});
	$('#rcmc_doi').datepicker({format: "dd/mm/yyyy"});
	$('#rcmc_validity').datepicker({format: "dd/mm/yyyy"});
	$('#shd_doi').datepicker({format: "dd/mm/yyyy"});
	$('#shd_validity').datepicker({format: "dd/mm/yyyy"});
	$('#cer_reg_date').datepicker({format: "dd/mm/yyyy"});
	
	//financial year
	$("#financial_year_0").html(options);
});

//disply only the selected category while editing
$(window).load(function() {
	//alert($('input:radio[name="entity[category]"]:checked').val());
	var classname =  $('input:radio[name="entity[category]"]:checked').attr('class');
	var classnameprefix = classname.split("_");
	$("[id^="+classnameprefix[0]+"]").hide();
	$("[id^="+classnameprefix[0]+"] :input").attr("disabled", "disabled");
	//$('[id^="+classnameprefix[0]+"] :input').find('input, textarea, button, select').attr('disabled','disabled');
	$("#"+classname).show();
	$("#"+classname+" :input").removeAttr("disabled");
  });

//financial year
var rowCount = $('#finance_row_count').val();
var count = 1; //for validation
var start = new Date().getFullYear();
var end = start-2;
var options = "";
for(var year = start ; year >=end; year--){
	prvyr = year-1;
	options += "<option>"+ prvyr + ' - '+ year +"</option>";
}

function addMoreRows(frm) {
	if(count == 3)
	{
		alert("You can only select upto last three financial years");
		return false;
	}
	rowCount ++;
	count++;
	
	var recRow = '<tr id="rowCount'+rowCount+'"><td colspan="1"><select name="turnover_details['+rowCount+'][financial_year]" id="financial_year_'+rowCount+'">'+options+'</select></td><td colspan="2"><input class="input-block-level" type="text" placeholder="" name="turnover_details['+rowCount+'][domestic_turnover]" id="domestic_turnover_'+rowCount+'"></td><td colspan="1"><input class="input-block-level" type="text" placeholder="" name="turnover_details['+rowCount+'][export_turnover]" id="export_turnover_'+rowCount+'"></td><td colspan="1"><a href="javascript:void(0);" onclick="removeRow('+rowCount+');"><i class="icon-minus"></i></a></td></tr>';
	jQuery('#finance_data').append(recRow);
}

function removeRow(removeNum) {
	jQuery('#rowCount'+removeNum).remove();
	count--;
}
</script>