<div id="error_message" class="alert alert-error" style="display: none;" <?php echo !empty($this->response['status']) && $this->response['status'] == 1 ? "" : "style='display: none;'"?>>Successfully Created</div>
<div style="height: 50px; float: right;">
	<a href="iec/addiec" class="btn btn-success" type="button">Add New IEC</a>
	<span style="padding-right: 15px"></span> 
	<!-- <a href="epcg/listsavedepcg" class="btn btn-warning" type="button">View Saved EPCG</a>
	<span style="padding-right: 15px"></span> 
	<a href="epcg/addepcg" class="btn btn-success" type="button">View Saved Chapter V</a>
	<span style="padding-right: 15px"></span> --> 
	<a href="epcg/addepcg" class="btn btn-warning" type="button">Add New EPCG</a>
</div>
<div style="clear: both;"></div>
<div style="height: 45px; text-align: center;">
	<strong>LIST OF APPLICATION FORM FOR ISSUE/MODIFICATION OF IMPORTER EXPORTER CODE (IEC) NUMBER</strong>
</div>
<div id="iec_lists">
	<table class="table table-hover table-bordered table-striped" <?php echo !empty($this->allentities) ? " id='displayIec'" : ''; ?>>  
		<thead>
			<tr>
				<th width="10px" style="text-align: center;"></th>
				<th width="10px" style="text-align: center;">&nbsp;</th>	
				 <!-- <th width="40px" style="text-align: center;">Sl No</th> -->	
				<th width="230px" style="text-align: center;">IEC Number</th>	
				<th width="235px" style="text-align: center;">Entity Name</th>	
				<th width="50px" style="text-align: center;">Status</th>	
				<th width="100px" style="text-align: center;" >Action</th>	
			</tr>
		</thead>
		<tbody>
		<?php if(!empty($this->allentities)){
				$i = 1;
				foreach ($this->allentities as $entity_details){
			?>
			
		<tr>
			<td id="<?php echo $entity_details['id']?>"></td>
			<td style="text-align: center;"><label class="checkbox"><input type="checkbox" class="check_iec" name="select_iec[]" id="select_iec_<?php echo $entity_details['id']?>" value="<?php echo $entity_details['id']?>" style = "float: left; margin-left: -10px;"></label></td>
		<!--	<td style="text-align: center;"><?php echo $i;?></td> -->	
			<td >
			 	<div style="max-width: 291px;word-wrap:break-word" id="iecnumber_<?php echo $entity_details['id']?>"><?php echo empty($entity_details['iec_number'])? 'Not Generated' : $entity_details['iec_number']?></div>
				<input class="input-block-level-sm" id="iectextbox_<?php echo $entity_details['id']?>" type="text" style="display:none; margin: 0px 0px; padding: 4px 5px; height: 12px; width: 250px;" />
			</td>
			<td><?php echo $entity_details['name'];?></td>
			<td><select  name="entity_status" id="entity_status_<?php echo $entity_details['id']?>" style="width: 100px; margin: 0px 0px; padding:0px 4px; height: 22px;">
					<?php foreach($this->allstatus as $status) {
						$selected = "";
						if($status['option_id'] == $entity_details['status'] )	{
							$selected = 'selected=selected';
							$option_value = $status['option_value'];
						}			
					?>
					<option value="<?php echo $status['option_id'].'_'.$entity_details['id'];?>" <?php echo $selected;?>><?php echo $status['option_value'];?></option>
					<?php }?>
				</select>
			</td>
			<td> 
				<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit" class="btn btn-mini btn-primary" type="button" id="editIec_<?php echo $entity_details['id']?>" href="iec/editiec?id=<?php echo $entity_details['id']?>"><i class="icon-edit"></i> </a>
				<button data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" class="btn btn-mini btn-danger" type="button" id="deleteIec_<?php echo $entity_details['id']?>" value="<?php echo $entity_details['id']?>"><i class="icon-trash"></i></button>
				<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Print" class="btn btn-mini btn-info" type="button" id="editIec_<?php echo $entity_details['id']?>" href="iec/editiec?id=<?php echo $entity_details['id']?>"><i class="icon-print"></i></a>
				<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Send Email" class="btn btn-mini btn-warning" type="button" id="editIec_<?php echo $entity_details['id']?>" href="iec/editiec?id=<?php echo $entity_details['id']?>"><i class="icon-envelope"></i></a>
			</td>
		</tr>
		<?php $i++;
				} ?> </tbody><?php }else{?>
		<tr>
			<td colspan="5" style="text-align: center;"> No Details found, Please click Add New IEC button to create a new application</td>
		</tr>
		<?php }?>
	</table>
</div>
<!-- 
<div class="pagination pagination-centered" style="padding-top: 15px">
  <ul>
    <li><a href="#">Prev</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</div> 
 -->
<div id="emailcategory" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<h5 id="myModalLabel">Select Email Category</h5>
	</div>
	<div class="modal-body">
		<?php echo $this->allemailcategories; ?>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button class="btn btn-primary" id="sendemailnotification">Send Email</button>
	</div>
</div>
<!--  
<div class="muted"><small>*Click on the IEC Number cell to update the IEC Number</small></div>
<div style="padding-top: 10px;" id="sendmail"><a href="#emailcategory" role="button" class="btn btn-warning" data-toggle="modal" >Send Mail</a></div>
-->
<link href="styles/jquery.dataTables.css" rel="stylesheet">
<script src="scripts/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function(){
	  var table =  $('table#displayIec').DataTable({
			columnDefs: [{ orderable: false, targets: [1,4,5]}],
			"columns": [
			            {
			                "className":      'details-control',
			                "orderable":      false,
			                "data":           null,
			                "defaultContent": ''
			            },
			            { "data": "&nbsp;" },
			            { "data": "IEC Number" },
			            { "data": "Entity Name" },
			            { "data": "Status" },
			            { "data": "Action" }
			        ],
			        "order": [[2, 'desc']]
	});
	$("select[name='displayIec_length']").attr('style', 'width: 70px');
// Add event listener for opening and closing details
	$('table#displayIec').on('click', 'td.details-control', function () {
	     var tr = $(this).closest('tr');
	     var row = table.row( tr );
	     var rowId =  $(this).attr('id');
	     if ( row.child.isShown() ) {
	         // This row is already open - close it
	         row.child.hide();
	         tr.removeClass('shown');
	     }
	     else {
	         // Open this row
	         getDetails(row.child,rowId);
	         //row.child(getDetails(rowId)).show();
	         tr.addClass('shown');
	     }
	});
		    
	// show send mail button only id check box is checked
	/* var sendmail = $("#sendmail").hide(),
	 checkboxselect = $("#displayEpcg").on("click","input[type=checkbox]",function() {
	    checkboxselect = $("#displayEpcg").on('click',function() {
		    sendmail.toggle( checkboxselect.is(":checked") );
		    sendmail.toggle(!checkboxselect.is(":checked"));
		    sendmail.toggle(checkboxselect.checked);
   		});
	 });
	*/  
});


function getDetails(callback,rowId) {
	$.ajax({
        url: '/public/epcg/get-all-epcg?iec_id='+rowId,
        dataType: "json",
        success: function (response) {
        	//var data = JSON.parse(response.responseText);
        	var thead = '';
        	var tbody = '';
        	alert(response.status);
            if (response.status == 2){
            	var tbody = '<tr><td>No EPCG Found</td><td><a href="epcg/addepcg" class="btn btn-warning" type="button">Add New EPCG</a></td></tr>';
            }
        /*  var tbody = '';
            $.each(data, function (i, d) {
                for (var x = 0; x < d.length ; x++)
                {
                    tbody += '<tr><td>' + x + '</td><td>' + 
                    '<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit" class="btn btn-mini btn-primary" type="button" id="" href=""><i class="icon-edit"></i> </a>&nbsp;'+
        			'<button data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" class="btn btn-mini btn-danger" type="button" id="deleteEpcg" value=""><i class="icon-trash"></i></button>&nbsp;'+
        			'<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Print" class="btn btn-mini btn-info" type="button" id="editEpcg_" href="epcg/editepcg?id="><i class="icon-print"></i></a>'+
                    '</td></tr>';
                }
            });*/
            callback($('<table class="table table-hover table-bordered table-striped">'+ thead  + tbody + '</table>')).show();
          
        },
        error: function () {
        	callback($('<table class="table table-hover table-bordered table-striped" style="margin: 0px;"><tr><td>There was an error getting the info! Please refresh and try again..</td></tr></table>')).show();
          //  $('#'+rowId).html('Bummer: there was an error!');
        }
	});  
    /*return '<table class="table table-hover table-bordered table-striped">'+
	    '<tr><td colspan="2"><b>Chapter V</b></td></tr>'+
        '<tr><td><b>Sl No</b></td><td><b>Actions</b></td></tr>'+
        '<tr>'+
            '<td>1</td>'+
            '<td><a data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit" class="btn btn-mini btn-primary" type="button" id="" href=""><i class="icon-edit"></i> </a>&nbsp;'+
			'<button data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" class="btn btn-mini btn-danger" type="button" id="deleteEpcg" value=""><i class="icon-trash"></i></button>&nbsp;'+
			'<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Print" class="btn btn-mini btn-info" type="button" id="editEpcg_" href="epcg/editepcg?id="><i class="icon-print"></i></a>'+'</td>'+
        '</tr>'+
        '<tr>'+
            '<td>2</td>'+
            '<td><a data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit" class="btn btn-mini btn-primary" type="button" id="" href=""><i class="icon-edit"></i> </a>&nbsp;'+
			'<button data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" class="btn btn-mini btn-danger" type="button" id="deleteEpcg" value=""><i class="icon-trash"></i></button>&nbsp;'+
			'<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Print" class="btn btn-mini btn-info" type="button" id="editEpcg_" href="epcg/editepcg?id="><i class="icon-print"></i></a>'+'</td>'+
        '</tr>'+
    '</table>';*/
}
</script>