<form action="chapterv/index" method="post" name="epcg_form" id="epcg_form" enctype="multipart/form-data">
	<div style="text-align: center;">
		<caption style="height: 60px">
				<strong>ANF - 5A</strong><br/>
				<strong>(Application Form for EPCG)</strong>
				<p>(Please see the guidellines before filling the application)</p>
		</caption>
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">1.</td>
			<td colspan="2">Application for</td>
			<td width="389px">Please tick</td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">a.</td>
			<td>EPCG Scheme</td>
			<td><input type="checkbox"	name="epcg[app_scheme]" value="1"></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Post Export EPCG Scheme</td>
			<td><input type="checkbox"	name="epcg[app_scheme]" value="2"></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">2.</td>
			<td>IEC No.</td>
			<td><input class="input-block-level" type="text" placeholder="IEC No" name="iec_no" id="iec_no" ></td>
			<td>Branch Code</td>
			<td><input class="input-block-level" type="text" placeholder="Branch Code" name="branch_code" id="branch_code" ></td>
		</tr>
		<tr>
			<td></td>
			<td colspan="2">Declaration: I/We have updated my/our profile in ANF - 1</td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Declaration" name="declaration" id="declaration" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">3.</td>
			<td>Address of the factory/premises of he applican where the capital goods to be imported are proposed to be installed</td>
		</tr>
		<tr>
			<td></td>
			<td>	
				<select name="factory_address" id="factory_address">
					<option value="0">--Select--</option>
				</select>
			</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">4.</td>
			<td colspan="3">Excise Registraion Details</td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">a.</td>
			<td width="350px">Excise Registration Number</td>
			<td><input class="input-block-level" type="text" placeholder="Registration Number" name="excise[registration_num]" id="excise_registration_num]" ></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Date of registration</td>
			<td><input class="input-block-level" type="text" placeholder="Date of Registration" name="excise[dor]" id="excise_dor" ></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>Address of the Jurisdictional Central Excise Auhority<br/>(whether registered with central excise or not)</td>
			<td><input class="input-block-level" type="text" placeholder="Address" name="excise[address]" id="excise_address" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td  width="20px">5.</td>
			<td width="387px">Port of Registration (for the purpose of imports)</td>
			<td>
				<select name="registered_port" id="registered_port">
					<option value="0">--Select--</option>
				</select>
			</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">6.</td>
			<td colspan="4">Application Fee Payment details </td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">a.</td>
			<td style="width: 350px">Amount (in Rs.)</td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Amount" name="app_fee[amount]" id="app_fee_amount" ></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>
				Mode of Payment<br/>
			   (TR Challan/Electronic Fund Transfer/Credit Cart)
			</td>
			<td colspan="2"><input class="input-block-level" type="text" placeholder="Mode of Payment" name="app_fee[payment_mode]" id="app_fee_payment_mode" ></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>
				Serial No. of TR challan/EFT no./credit card details and Date of Payment
			</td>
			<td><input class="input-block-level" type="text" placeholder="Payment Details" name="app_fee[payment_details]" id="app_fee_payment_details" ></td>
			<td><input class="input-block-level" type="text" placeholder="Date of Payment" name="app_fee[payment_date]" id="app_fee_payment_date" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">7.</td>
			<td colspan="3">Service Tax Registration Details (in case of Service Providers registered with Service Tax Authoities)</td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">a.</td>
			<td style="width: 350px">Service Tax Registration Number</td>
			<td><input class="input-block-level" type="text" placeholder="Registration Number" name="service_tax[registraion_num]" id="service_tax_registration_num" ></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Date of registration</td>
			<td><input class="input-block-level" type="text" placeholder="Date of Registration" name="service_tax[dor]" id="service_tax_dor" ></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>Address of Jurisdictional Service Tax Authoriy</td>
			<td><input class="input-block-level" type="text" placeholder="Address" name="service_tax[auth_address]" id="service_tax_auth_address" ></td>
		</tr>
		<tr>
			<td></td>
			<td>d.</td>
			<td>Services for which registered</td>
			<td><input class="input-block-level" type="text" placeholder="Registered Services" name="service_tax[reg_services]" id="service_tax_reg_services" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">8.</td>
			<td colspan="3">Sector Classification of Capital Gods sought to be imported under the Scheme</td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">a.</td>
			<td width="350px;">Industrial Sector</td>
			<td><input type="checkbox"	name="sector" value="1"></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Agricultural Sector</td>
			<td><input type="checkbox"	name="sector" value="2"></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>Service Sector</td>
			<td><input type="checkbox"	name="sector" value="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>d.</td>
			<td>Green Technology Sector</td>
			<td><input type="checkbox"	name="sector" value="4"></td>
		</tr>
		<tr>
			<td></td>
			<td>e.</td>
			<td>Units in North Eastern Region/Sikkim/J&amp;K</td>
			<td><input type="checkbox"	name="sector" value="5"></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">9.</td>
			<td>Products to be exported/services to be rendered</td>
			<td>ITC(HS) Code/Service Code</td>
		</tr>	
		<tr>
			<td></td>
			<td><input class="input-block-level" type="text" placeholder="Product List" name="product_list" id="product_list" ></td>
			<td><input class="input-block-level" type="text" placeholder="ITC(HS)/Service Code" name="itc_code" id="itc_code" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">10.</td>
			<td colspan="3">Details of exports of same/similar product/services made in the preceding three licensing years (excluding exports which have been counted are being counted for fulfilling specific EO in respect of EPCG Authorizations within valid EO Period)</td>
		</tr>	
		<tr>
			<td></td>
			<td width="20px">Sl. No.</td>
			<td>Financial Year</td>
			<td>Total FOB Value of exports/services rendered for the same/similar product/services (Rs. in crores)</td>
		</tr>	
		<tr>
			<td></td>
			<td>1</td>
			<td width="400px"><input class="input-block-level" type="text" placeholder="Financial Year" name="financial_year[]" id="financial_year_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Total Value" name="total_fob_value[]" id="total_fob_value_1" ></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>Total</td>
			<td><input class="input-block-level" type="text" placeholder="Total" name="total_value" id="total_value" readonly="readonly"></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>*Average export performance</td>
			<td><input class="input-block-level" type="text" placeholder="Average export performance" name="avg_export_perf" id="avg_export_perf" readonly="readonly"></td>
		</tr>
	</table>
	<div>* If the applicant has been in exisence for less then 3 years, the aggregate export will be divided by the number of years for thich the company has been in existence and not by 3 years</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">11.</td>
			<td colspan="8">Details of EPCG Authorizations where EO is pending</td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">Sl.No.</td>
			<td>Authorizaion No. and Date</td>
			<td>RA which issued the Authorization</td>
			<td>Value of duty saved/duty paid 9 (in Rs.)</td>
			<td>EO fixed on duty saved/duty paid (in freely convertible currency)/Rs.</td>
			<td>Specific EO fulfilled</td>
			<td>Annual Average EO fixed (in Rs.)</td>
			<td>Expiry date of EO period</td>
		</tr>
		<tr>
			<td></td>
			<td>1</td>
			<td>
				<input class="input-block-level" type="text" placeholder="Auth No" name="epcg_auth[num][]" id="epcg_auth_num_1" >
				<input class="input-block-level" type="text" placeholder="Date" name="epcg_auth[date][]" id="epcg_auth_date_1" >
			</td>
			<td>
				<input class="input-block-level" type="text" placeholder="RA Details" name="epcg_auth[ra_details][]" id="epcg_auth_ra_details_1" >
			</td>
			<td><input class="input-block-level" type="text" placeholder="Value" name="epcg_auth[duty_saved_paid][]" id="epcg_auth_duty_saved_paid_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Value" name="epcg_auth[eo_fixed][]" id="epcg_auth_ec_fixed_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Value" name="epcg_auth[eo_fullfilled][]" id="epcg_auth_eo_fullfilled_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Value" name="epcg_auth[eo_average][]" id="epcg_auth_eo_average_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Date" name="epcg_auth[eo_expiry_date][]" id="epcg_auth_eo_expiry_date_1" ></td>
		</tr>
	</table>	
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>12.</td>
			<td colspan="6">Details of Capital goods to be imported</td>
		</tr>
		<tr>
			<td></td>
			<td  width="20px">Sl.No.</td>
			<td>Description of the items of import</td>
			<td>ITC(HS) Code</td>
			<td>Nature of Captal Goods sought to be imported*</td>
			<td>Quantity</td>
			<td>Primary use of Capital Goods sought to be imported**</td>
		</tr>
		<tr>
			<td></td>
			<td>1</td>
			<td><input class="input-block-level" type="text" placeholder="Items Description" name="import_goods[description][]" id="import_goods_description_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="ITC(HS) Code" name="import_goods[itc_code][]" id="import_goods_itc_code_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Goods Nature" name="import_goods[nature][]" id="import_goods_nature_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Quantity" name="import_goods[quantity][]" id="import_goods_quantity_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Primary Use" name="import_goods[primary_use][]" id="import_goods_primary_use_1" ></td>
		</tr>
	</table>
	<div style="padding-bottom: 10px">
		* whether Capial Goods/Spares/Tools/Jigs/Fixtures/Dies/Mouldes/Spare refractories/Catalyst(specify if any other)<br/>
		** whether used for Pre-production acitivity/Production activity/Post-production activity/for rendering services
	</div>	
	<div  style="padding-bottom: 20px">
		13. Whether product to be imported is restricted for import - 
		<input type="radio" name="entity_category" value="entity_partnership">Yes
		<input type="radio" name="entity_category" value="entity_partnership">No
		<br/>
		(If yes, enclose copy of EFC approva from DGFT Hqrs.)
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">14.</td>
			<td colspan="5">Details of Restricted Capital Goods applied for import</td>
		</tr>
		<tr>
			<td></td>
			<td width="20px">Sl.No.</td>
			<td>Description of the items of import</td>
			<td>ITC(HS) Code</td>
			<td>Nature of Capital Goods sought to be imported*</td>
			<td>Primary use of Capial Goods sought to be imported**</td>
		</tr>
		<tr>
			<td></td>
			<td>1</td>
			<td><input class="input-block-level" type="text" placeholder="Items Description" name="import_goods_restricted[description][]" id="import_goods_restricted_description_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="ITC(HS) Code" name="import_goods_restricted[itc_code][]" id="import_goods_restricted_itc_code_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Goods Nature" name="import_goods_restricted[nature][]" id="import_goods_restricted_nature_1" ></td>
			<td><input class="input-block-level" type="text" placeholder="Primary Use" name="import_goods_restricted[primary_use][]" id="import_goods_restricted_primary_use_1" ></td>
		</tr>
	</table>
	<div style="padding-bottom: 10px">
		* whether Capital Goods/Spares/Tols/jigs/Fixures/Dies/Moulds/Spare refractories/Catalyst (specify if any other) <br/>
		** whether used for Pre-production activity/Prduction activity/Ps-production activity/for rendering services <br/>
		(From amongst column 13 and 14 above please fill up whichever is applicable. In case applican desires to import <br/>
		both restricted and free importable capital goods appropriate information should be given in both the columns).
	</div>
	<div style="padding-bottom: 15px">
		15. Whether product to be exported is restricted for export - <input type="radio" name="entity_category" value="entity_partnership">Yes
		<input type="radio" name="entity_category" value="entity_partnership">No<br/><br/>
		(If yes, enclose copy of EFC apprval from DGF Hqrs.)
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">16.</td>
			<td colspan="3">Details of Duty</td>
		</tr>
		<tr>
			<td></td>
			<td>Total effective Customs duty on items to be imported (in %)</td>
			<td>CIF value of imports/deemed imports (in Rs.)</td>
			<td>Duty saved amount (in Rs.)</td>
		</tr>
		<tr>
			<td></td>
			<td  width="275px"><input class="input-block-level" type="text" placeholder="Total" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="CIF value" name="cif_value" id="cif_value" ></td>
			<td><input class="input-block-level" type="text" placeholder="Duty saved amount" name="duty_saved_amount" id="duty_saved_amount" ></td>
		</tr>
	</table>
	<div style="padding-bottom: 15px">
		Note: In case of indigenous sourcing of CG, duty saved is to be calculated on notional customs duty saved on FOR value f capial goods as per <br/>Para 5.07 of FTP.
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">17.</td>
			<td colspan="4">Details of Duty in case of posr-expr EPCG duty credit scrip</td>
		</tr>
		<tr>
			<td></td>
			<td>Total effective Customs duty on items to be imported (in %)</td>
			<td>Basic Customs duty</td>
			<td>CIF value of imports/deemed imports (in Rs.)</td>
			<td>Duty paid  (in Rs.)</td>
		</tr>
		<tr>
			<td></td>
			<td><input class="input-block-level" type="text" placeholder="Total" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="Basic Customs Duty" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="CIF Value" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="Duty Paid" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">18.</td>
			<td colspan="4">Details of Export Obligation imposed</td>
		</tr>
		<tr>
			<td></td>
			<td>Total duty saved/duty paid (Rs.)</td>
			<td colspan="2">Specific Export Obligation to be imposed</td>
			<td>Average Export Obligation to be imposed</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>Rs.</td>
			<td>USD</td>
			<td>Rs.</td>
		</tr>
		<tr>
			<td></td>
			<td><input class="input-block-level" type="text" placeholder="" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
			<td><input class="input-block-level" type="text" placeholder="" name="total_effective_customs_duty" id="total_effective_customs_duty" ></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">19.</td>
			<td>
				Address of the factory/premises of the application or the supporting manufacurer where the capital goods to<br/>
				be imported are proposed to be installed
			</td>
		</tr>
		<tr>
			<td></td>
			<td><input class="input-block-level" type="text" placeholder="" name="Address" id="address"></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">20.</td>
			<td colspan="3">In case the prposed capital goods sought to be imported are to be used by the supporting manufacturer</td>	
		</tr>
		<tr>
			<td></td>
			<td width="20px">a.</td>
			<td width="450px">Name</td>
			<td><input class="input-block-level" type="text" placeholder="Name" name="name" id="address"></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Address</td>
			<td><input class="input-block-level" type="text" placeholder="Address" name="address" id="address"></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>MSME/IEM/LOI/IL Registration No. and date</td>
			<td>
				<input class="input-block-level" type="text" placeholder="MSME/IEM/LOI/IL Registration No" name="reg_num" id="address">
				<input class="input-block-level" type="text" placeholder="Date" name="date" id="date">
			</td>
		</tr>
		<tr>
			<td></td>
			<td>d.</td>
			<td>Products endorsed on MSME/LOI/IL/IEM</td>
			<td><input class="input-block-level" type="text" placeholder="Products endorsed on MSME/LOI/IL/IEM" name="products_endorsed" id="address"></td>
		</tr>
		<tr>
			<td></td>
			<td>e.</td>
			<td>Excise Registration No. and issuing authoriy, (if applicable)</td>
			<td>
				<input class="input-block-level" type="text" placeholder="Registration Number" name="Address" id="address">
				<input class="input-block-level" type="text" placeholder="Issuing Authority" name="Address" id="address">
			</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td width="20px">21.</td>
			<td>
				Postal address f the jurisdictional Central Excise Authoriy in whose jurisdiction factory/premises of the<br/>
				applicant/supporting manufacurer where the capital goods to be imported are proposed to be installed.
			
			</td>	
		</tr>
		<tr>
			<td></td>
			<td><input class="input-block-level" type="text" placeholder="Address" name="address" id="address"></td>
		</tr>
	</table>
	<div style="text-align: center;font-weight: bold;height: 30px;">DECLARATION/UNDERTAKING</div>
	<div>
		<ol>
			<li>I / We hereby declare that the particulars and the statements made in this application are true and correct to the best of my/our knowledge and belief and nothing has been concealed or held there from and if found incorrect or false will render me/us liable for any penal action or other consequences as may be prescribed in law or otherwise warranted.</li>
			<li>I / We undertake to abide by the provisions of the Foreign Trade (Development and Regulation) Act, 1992, the Rules and Orders framed there under, the Foreign Trade Policy, the Handbook of Procedures and the ITC(HS) Classification of Export &amp; Import Items.</li>
			<li>I / We hereby certify that none of the Proprietor / Partner(s) / Director(s) / Karta / Trustee of the firm / company, as the case may be, is/are a Proprietor / Partner(s) / Director(s) / Karta / Trustee in any other firm / Company which has come to the adverse notice of DGFT.</li>
			<li>I / We hereby certify that neither the Registered Office/Head Office of the firm/company nor any of its Branch Office(s) / Unit(s) / Division(s) has been declared a defaulter and has otherwise been made ineligible for undertaking import / export under any of the provisions of the Policy.</li>
			<li>I / We hereby certify that our applicant firm/company is NOT currently availing any benefits under Technology Upgradation Fund Scheme (TUFS), administered by Ministry of Textiles, Government of India. (Applicable to zero duty EPCG scheme only)</li>
			<li>I / We hereby certify that our applicant firm/company has NOT availed and shall not avail the benefit of Status Holder Incentive Scheme under Para 3.16 of FTP in the current year. (Applicable to zero duty EPCG scheme only)</li>
			<li>I / We hereby declare that I/we have perused the list of SCOMET items as contained in the Appendix 3 to the Schedule 2 of the ITC (HS) Classifications of Export-Import Items, 2004-09 and that the item(s) exported / proposed to be exported does not fall within this list and that I/ We agree to abide by the provisions of the Policy for export of SCOMET items contained in the Foreign Trade Policy, Schedule 2 of ITC (HS) and the Handbook of Procedures (Vol.1), irrespective of the scheme under which the item is exported / proposed to be exported.</li>
			<li>I / We declare that no export proceeds are outstanding beyond the prescribed period as laid down by the RBI, or such extended period for which RBI permission has been obtained.</li>
			<li>I / We hereby declare that the capital goods/spares sought for import in the application are actually required for use at pre production/production/post production stages for the export product(s) or for rendering services for fulfillment of export obligation.</li>
			<li>I / We hereby declare that in respect of goods for which nexus is not established at a later date, I / We shall pay to the Government Customs duty saved together with 15% interest on such imported goods which are found having no relation with product exported or service rendered.</li>
			<li>I / We hereby declare that in case of import of refurbished/reconditioned spares, the refurbished/reconditioned spares have a residual life which is not less than 80% of the life of the original spares.</li>
			<li>I / We hereby declare that I / We do not come under the purview of Service Tax and therefore are not registered with the Service Tax Cell of the jurisdictional Central Excise Authorities. (in case of Service Providers who are not covered under service tax)</li>
			<li>I / We hereby declare that I/We shall not exceed the SSI investment limit in plant and machinery after making imports under the EPCG Authorisation. (applicable in cases of imports made by SSI sector)</li>
			<li>I / We hereby declare that the import of capital goods shall be used for building and operating shopping malls/super markets having a minimum covered area of 1000 sq meters. (Applicable in case of imports made by Retail sector).</li>
			<li>I / We hereby declare that I/We have not made imports under the Technological Upgradation Scheme previously before any Licensing authority and the present imports of Capital Goods to be made under this Scheme (for which this application is made) are more than 10% of the my/our present investment in the plant and machinery. (Applicable in case of imports under EPCG Technological Upgradation Scheme).</li>
			<li>I / We undertake to submit a self certified copy of 'Drug Manufacturing Licence' in case of export of Pharmaceutical Product(s) within a period of three years from the date of issue of EPCG Authorization failing which the Bank Guarantee / Legal undertaking executed / furnished at the time of clearance of Capital Goods with Customs authorities / Regional Authorities of DGFT, as the case may be, is liable to be forfeited / invoked and I / We would be liable to pay Customs Duty saved amount together with applicable interest thereon from the date of first import till the date of final payment.</li>
			<li>I hereby certify that I am authorized to verify and sign this declaration as per Paragraph 9.9 of the Policy. </li>
		</ol>
	</div>
	<div>(Note: Strike out the clause which is not applicable.)</div>
	<div style="text-align: center;padding-top: 25px;">
		<button type="submit" class="btn btn-primary" name="submitform" value="Submit Form" id="submit_epcgform">Submit</button> 
		<span style="padding-right: 25px"></span>
		<button type="submit" class="btn btn-warning" name="saveform" value="Save Form"  id="save_epcgform">Save</button>
		<span style="padding-right: 25px"></span> 
		<button type="reset" class="btn btn-danger">Reset</button>
		<span style="padding-right: 25px"></span> 
		<a href="epcg/index" type="button" class="btn btn-inverse">Back</a>
		<!-- 
		<span style="padding-right: 25px"></span> 
		<a href="#" type="button" class="btn btn-warning">Print</a>
		 -->
	</div>
</form>
<script>
$(function(){
    $('#excise_dor').datepicker({});
	$('#app_fee_payment_date').datepicker({});
	$('#service_tax_dor').datepicker({});
	$('#epcg_auth_date_1').datepicker({});
	$('#epcg_auth_eo_expiry_date_1').datepicker({});
	
});
</script>