
<div style="height: 50px; float: right;">
	<a href="epcg/listsavedepcg" class="btn btn-warning" type="button">Edit Saved EPCG</a>
	<span style="padding-right: 15px"></span> 
	<a href="epcg/addepcg" class="btn btn-success" type="button">Add New EPCG</a>
</div>
<div style="clear: both;"></div>
<div style="height: 45px; text-align: center;">
	<strong>LIST OF APPLICATION FORM FOR ISSUE/MODIFICATION OF IMPORTER EXPORTER CODE (IEC) NUMBER</strong>
</div>
<table class="table table-hover table-bordered table-striped" <?php echo !empty($this->allentities) ? " id='displayEpcg'" : ''; ?>>  
<thead>
	<tr>
		<th width="40px" style="text-align: center;">Sl No</th>	
		<th width="200px" style="text-align: center;">IEC No</th>	
		<th width="300px" style="text-align: center;">Entity Name</th>	
		<th width="50px" style="text-align: center;">Status</th>	
		<th width="57px" style="text-align: center;" >Action</th>	
	</tr>
	 </thead>
	  <tbody>
	<?php if(!empty($this->allentities)){
			$i = 1;
			foreach ($this->allentities as $entity_details){
		?>
		
	<tr>
		<td style="text-align: center;"><?php echo $i;?></td>
		<td><?php echo empty($entity_details['iec_no'])? 'Not Generated' : $entity_details['iec_no']?></td>
		<td><?php echo $entity_details['name'];?></td>
		<td><select  name="entity_status" id="entity_status_<?php echo $entity_details['id']?>" style="width: 100px; margin: 0px 0px; padding:0px 4px; height: 22px;">
				<?php foreach($this->allstatus as $status) {
					$selected = "";
					if($status['option_id'] == $entity_details['status'] )	{
						$selected = 'selected=selected';
						$option_value = $status['option_value'];
					}			
				?>
				<option value="<?php echo $status['option_id'].'_'.$entity_details['id'];?>" <?php echo $selected;?>><?php echo $status['option_value'];?></option>
				<?php }?>
			</select>
		</td>
		<td> 
			<button class="btn btn-mini btn-primary" type="button" id="editEpcg" value="<?php echo $entity_details['id']?>">Edit</button>
			<button class="btn btn-mini btn-danger" type="button" id="deleteEpcg_<?php echo $entity_details['id']?>" value="<?php echo $entity_details['id']?>">Delete</button>
		</td>
	</tr>
	<?php $i++;
			} ?> </tbody><?php }else{?>
	<tr>
		<td colspan="5" style="text-align: center;"> No Details found, Please click Add New EPCG button to create a new application</td>
	</tr>
	<?php }?>
</table>
<!-- 
<div class="pagination pagination-centered" style="padding-top: 15px">
  <ul>
    <li><a href="#">Prev</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</div> 
 -->

<link href="styles/jquery.dataTables.css" rel="stylesheet">
<script src="scripts/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
	 $('table#displayEpcg').DataTable({
			columnDefs: [{ orderable: false, targets: [3,4]}],
	  });
	 $("select[name='displayEpcg_length']").attr('style', 'width: 70px');
} );
</script>