<div style="height: 50px; float: right;">
	<a href="epcg/addepcg" class="btn btn-success" type="button">Add New EPCG</a>
</div>
<div style="clear: both;"></div>
<div style="height: 45px; text-align: center;">
	<strong>LIST OF APPLICATION FORM FOR ISSUE/MODIFICATION OF IMPORTER EXPORTER CODE (IEC) NUMBER</strong>
</div>
<table class="table table-hover table-bordered table-striped"  id="display">  
<thead>
	<tr>
		<th width="40px">Sl No</th>	
		<th width="200px">IEC No</th>	
		<th width="320px">Name</th>	
		<th width="70px">Status</th>	
		<th width="75px">Action</th>	
	</tr>
	 </thead>
	  <tbody>
	<?php if(!empty($this->allentities)){
			$i = 1;
			foreach ($this->allentities as $entity_details){
		?>
		
	<tr>
		<td style="text-align: center;"><?php echo $i;?></td>
		<td><?php echo empty($entity_details['iec_no'])? 'Not Generated' : $entity_details['iec_no']?></td>
		<td><?php echo $entity_details['name'];?></td>
		<td><select  name="entity_status" id="entity_status">
				<?php foreach($this->allstatus as $status) {
					$selected = "";
					if($status['id'] == $entity_details['status'] )	{
						$selected = 'selected=selected';
					}			
				?>
				<option value="<?php echo $status['id'].'_'.$entity_details['id'];?>" <?php echo $selected;?>><?php echo $status['status'];?></option>
				<?php }?>
			</select>
		</td>
		<td> <button class="btn btn-info" type="button">Edit</button></td>
	</tr>
	<?php $i++;
			} ?> </tbody><?php }else{?>
	<tr>
		<td colspan="5" style="text-align: center;"> No Details found, Please click Add New EPCG button to create a new application</td>
	</tr>
	<?php }?>
</table>
<!-- 
<div class="pagination pagination-centered" style="padding-top: 15px">
  <ul>
    <li><a href="#">Prev</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</div> 
 -->

<link href="styles/jquery.dataTables.css" rel="stylesheet">
<script src="scripts/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
	 $('table#display').DataTable();
	 $("select[name='display_length']").attr('style', 'width: 70px');
} );
</script>