<div style="height: 50px; float: right;">
	<a href="epcg/index" class="btn btn-warning" type="button">View EPCG</a>
	<span style="padding-right: 15px"></span> 
	<a href="epcg/addepcg" class="btn btn-success" type="button">Add New EPCG</a>
</div>
<div style="clear: both;"></div>
<div style="height: 45px; text-align: center;">
	<strong>LIST OF SAVED EPCG FORM</strong>
</div>
<table class="table table-hover table-bordered table-striped" <?php echo !empty($this->allentities) ? " id='displayEpcg'" : ''; ?> >  
<thead>
	<tr>
		<th width="40px" style="text-align: center;">Sl No</th>	
		<th width="250px" style="text-align: center;">Entity Name</th>	
		<th width="200px" style="text-align: center;">Nature of Entity</th>	
		<th width="100px" style="text-align: center;">Created By</th>	
		<th width="51px" style="text-align: center;">Action</th>	
	</tr>
	 </thead>
	  
	<?php if(!empty($this->allentities)){?>
	<tbody>
		<?php 	$i = 1;
			foreach ($this->allentities as $entity_details){
		?>
		
	<tr>
		<td style="text-align: center;"><?php echo $i;?></td>
		<td><?php echo $entity_details['name'];?></td>
		<td><?php echo $entity_details['category'];?></td>
		<td><?php echo $entity_details['created_by'];?></td>
		<td>
			<button class="btn btn-mini btn-primary" type="button" id="editEpcg" value="<?php echo $entity_details['id']?>">Edit</button>
			<button class="btn btn-mini btn-danger" type="button" id="deleteEpcg_<?php echo $entity_details['id']?>" value="<?php echo $entity_details['id']?>">Delete</button>
		</td>
	</tr>
	<?php $i++;
			} ?> </tbody><?php }else{?>
	<tr>
		<td colspan="5" style="text-align: center;"> No saved EPCG forms found, please click Add New EPCG button to create a new application</td>
	</tr>
	<?php }?>
</table>
<!-- 
<div class="pagination pagination-centered" style="padding-top: 15px">
  <ul>
    <li><a href="#">Prev</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</div> 
 -->

<link href="styles/jquery.dataTables.css" rel="stylesheet">
<script src="scripts/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
	 $('table#displayEpcg').DataTable({
			columnDefs: [{ orderable: false, targets: [4]}],
	  });
	 $("select[name='displayEpcg_length']").attr('style', 'width: 70px');
} );
</script>