<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Shree Impex</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<base href="<?php echo $this->config['url']['base'];?>" />
<!-- styles -->
<link href="styles/bootstrap.css" rel="stylesheet">
<link href="styles/style.css" rel="stylesheet">
<link href="styles/bootstrap-responsive.css" rel="stylesheet">
<link href="styles/datepicker.css" rel="stylesheet">
<link href="styles/star-rating.css" rel="stylesheet">

<!-- scripts -->
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="scripts/html5shiv.js"></script>
    <![endif]-->

<!-- Fav and touch icons -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="ico/favicon.png">

<style>
body {
	background-color: #fff;
	background-image: url("images/bg.png");
	background-repeat: repeat-x;
}
</style>
</head>
<body>
	<div class="container"> 
		<?php if(isset($this->session->user)){?>
		<div style="float: left;"><h3 class="muted" id="logo"><img alt="shreeimpex" src="images/shreeimpex.png"></h3></div>
		<div id="welcomeTag">Welcome <?php echo ucwords($this->session->user->user_firstname).' '.ucwords($this->session->user->user_lastname)?> 
		<span style=" border-left: 1px solid rgba(70,70,70,.75); padding-left: 4px;"></span><a id="logout" href="index/logout"> Log Out</a></div>
		<div style="clear: both;"></div>
		<div style="padding-top: 50px"></div>
		<div class="masthead">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
							<li><a href="home">Home</a></li>
							<!-- <li><a href="#">Projects</a></li> 
							<!-- <li class="dropdown"><a class="dropdown-toggle"
								data-toggle="dropdown" href="#"> EPCG <b class="caret"></b>
								</a>
								<ul class="dropdown-menu" role="menu"
									aria-labelledby="dropdownMenu">
									<li><a tabindex="-1" href="epcg">View EPCG</a></li>
									<li><a tabindex="-1" href="epcg/addepcg">Add EPCG</a></li>
									<!-- <li><a tabindex="-1" href="#">Something else here</a></li>
									<li class="divider"></li>
									<li><a tabindex="-1" href="#">Separated link</a></li> 
								</ul>
							</li>-->
							<li><a href="#">About</a></li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">Services <b class="caret"></b></a>
								<ul class="dropdown-menu" >
									<li class="dropdown-submenu">
										<a tabindex="-1" href="iec">IEC</a>
										<ul class="dropdown-subsubmenu">
											<li><a tabindex="-1" href="iec/addiec">Add New IEC</a></li>
											<li><a tabindex="-1" href="iec/listsavediec">View Saved IEC</a></li>
										<!-- 	<li><a tabindex="-1" href="epcg/addepcg">Add New EPCG</a></li>
											<li><a tabindex="-1" href="epcg/listsavedepcg">View Saved EPCG</a></li>-->
										</ul>
									</li>
									<!-- <li class="dropdown-submenu">
										<a tabindex="-1" href="epcg">Chapter V</a>
										<ul class="dropdown-subsubmenu">
										</ul>
									</li> -->
								</ul>
							</li>
							<li><a href="home/contactus">Contact Us</a></li>
							<?php if($this->session->user->user_role == 1){?>
							<li><a href="settings">Settings</a></li>
							<?php }?>
						 	<li ><a href="index">Site Map</a></li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /.navbar -->
		</div>
		<div id="content">
		<?php echo $this->layout()->content;?>
		<div style="clear: both;"></div>
		</div>
		<div class="footer">
			<p>&copy; Shree Impex 2015. All Rights Reserved.</p>
		</div>
		<?php }else{ ?>
			<div style="padding-left: 375px;"><h3 class="muted"><img alt="shreeimpex" src="images/shreeimpex.png"></h3></div>
			<?php echo $this->layout()->content; ?>
		<div class="footer" style="color: #fff;">
			<p>&copy; Shree Impex 2015. All Rights Reserved.</p>
		</div>
		<?php }?>
		

	</div>
	
	<!-- /container -->

	<!-- javascripts -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="scripts/bootstrap-tab.js"></script>
	<script src="scripts/bootstrap-dropdown.js"></script>
	<script src="scripts/bootstrap-tooltip.js"></script>
	<script src="scripts/custom/iec.js"></script>
	<script src="scripts/bootstrap-modal.js"></script>
	
	<script src="scripts/bootbox.js"></script>
	<script src="scripts/bootstrap-datepicker.js"></script>
	<script src="scripts/star-rating.js"></script>
	
<!-- <script src="scripts/bootstrap.min.js"></script>

	<script src="scripts/bootstrap-alert.js"></script>
	<script src="scripts/bootstrap-transition.js"></script>
	<script src="scripts/bootstrap-scrollspy.js"></script>
	
	<script src="scripts/bootstrap-popover.js"></script>
	<script src="scripts/bootstrap-button.js"></script>
	<script src="scripts/bootstrap-collapse.js"></script>
	<script src="scripts/bootstrap-carousel.js"></script>
	<script src="scripts/bootstrap-typeahead.js"></script>-->
	<script>
	$(".dropdown-submenu").mouseleave(function(){
	      $(".dropdown").removeClass("open");
	 });
	</script>
</body>
</html>
