<form action="chapterv/index" method="post" name="epcg_form" id="epcg_form" enctype="multipart/form-data">
	<div style="text-align: center;">
		<caption style="height: 60px">
				<strong>ANF - 5A</strong><br/>
				<strong>(Application Form for Issurance of EPCG/Post Export EPCG Auhorization)</strong>
				<p>(Please see the guidellines before filling the application)</p>
		</caption>
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>1.</td>
			<td colspan="2">Application for</td>
			<td>Please tick</td>
		</tr>
		<tr>
			<td></td>
			<td>a.</td>
			<td>EPCG Scheme</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Pos Export EPCG Scheme</td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>2.</td>
			<td>IEC No.</td>
			<td></td>
			<td>Branch Code</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td colspan="2">Declaration: I/We have updated my/our profile in ANF - 1</td>
			<td colspan="2"></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>3.</td>
			<td></td>
			<td>Address of the factory/premises of he applican where the capital goods to be imported are proposed to be installed</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>4.</td>
			<td colspan="3">Excise Registraion Details</td>
		</tr>
		<tr>
			<td></td>
			<td>a.</td>
			<td>Excise Registration Number</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Date of registration</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>
				Address of the Jurisdictional Central Excise Auhority<br/>
				(whether registered with central excise or not)
			</td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>5.</td>
			<td>Port of Registration (for the purpose of imports)</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>6.</td>
			<td colspan="3">Application Fee Payment details</td>
		</tr>
		<tr>
			<td></td>
			<td>a.</td>
			<td>Amount (in Rs.)</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>
				Mode of Payment
			   	(TR Challan/Electronic Fund Transfer/Credit Cart)
			</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>
				Serial No. of TR challan/EFT no./credit card details and Date of Payment
			</td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>7.</td>
			<td colspan="3">Service Tax Registration Details (in case of Service Providers registered with Service Tax Authoities)</td>
		</tr>
		<tr>
			<td></td>
			<td>a.</td>
			<td>Service Tax Registration Number</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Date of registration</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>Address of Jurisdictional Service Tax Authoriy</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>d.</td>
			<td>Services for which registered</td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>8.</td>
			<td colspan="3">Sector Classification of Capital Gods sought to be imported under the Scheme</td>
		</tr>
		<tr>
			<td></td>
			<td>a.</td>
			<td>Industrial Sector</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Agricultural Sector</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>Service Sector</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>d.</td>
			<td>Green Technology Sector</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>e.</td>
			<td>Units in North Eastern Region/Sikkim/J&K</td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>9.</td>
			<td>Products o be exprted/services to be rendered</td>
			<td>ITC(HS) Code/Service Code</td>
		</tr>	
		<tr>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>10.</td>
			<td colspan="3">Details of exports of same/similar product/services made in the preceding hress licensing years (excluding exports which have been counted are being counted for fulfilling specific EO in respect of EPCG Authorizations within valid EO Period)</td>
		</tr>	
		<tr>
			<td></td>
			<td>Sl. No.</td>
			<td>Financial Year</td>
			<td>Total FOB Value of exports/services rendered for the same/similar product/services (Rs. in crores)</td>
		</tr>	
		<tr>
			<td></td>
			<td>1</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>Total</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>*Average export performance</td>
			<td></td>
		</tr>
	</table>
	<div>* If the applicant has been in exisence for less then 3 years, the aggregate export will be divided by the number of years for thich the company has been in existence and not by 3 years</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>11.</td>
			<td colspan="8">Details of EPCG Authorizations where EO is pending</td>
		</tr>
		<tr>
			<td></td>
			<td>Sl.No.</td>
			<td>Authorizaion No. and Date</td>
			<td>RA which issued the Authorization</td>
			<td>Value of duty saved/duty paid 9 (in Rs.)</td>
			<td>EO fixed on duty saved/duty paid (in freely convertible currency)/Rs.</td>
			<td>Specific EO fulfilled</td>
			<td>Annual Average EO fixed (in Rs.)</td>
			<td>Expiry dae of EO period</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table>	
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>12.</td>
			<td colspan="6">Details of Capital goods to be imported</td>
		</tr>
		<tr>
			<td></td>
			<td>Sl. No.</td>
			<td>Description of he items of import</td>
			<td>ITC(HS) Code</td>
			<td>Nature of Captal Goods sought to be imported*</td>
			<td>Quantity</td>
			<td>Primary use of Capital Goods sought to be imported**</td>
		</tr>
	</table>
	<div>
		*whether Capial Goods/Spares/Tools/Jigs/Fixtures/Dies/Mouldes/Spare refractories/Catalyst(specify if any other)<br/>
		** whether used for Pre-production acitivity/Production activity/Post-production activity/for rendering services
	</div>	
	<div>
		13. Whether produc to be imported is resriced for import - Yes/No <br/>
		(If yes, enclose copy of EFC approva from DGFT Hqrs.)
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>14.</td>
			<td colspan="5">Details of Retriced Capital Goods applied for import</td>
		</tr>
		<tr>
			<td></td>
			<td>Sl.No.</td>
			<td>Description of the items of import</td>
			<td>ITC(HS) Code</td>
			<td>Nature of Capital Goods sought to be imported*</td>
			<td>Primary use of Capial Goods sought to be imported**</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table>
	<div>
		*whether Capital Goods/Spares/Tols/jigs/Fixures/Dies/Moulds/Spare refractories/Catalyst (specify if any other) <br/>
		**whether used for Pre-production activity/Prduction activity/Ps-production activity/for rendering services <br/>
		(From amongst column 13 and 14 above please fill up whichever is applicable. In case applican desires to import <br/>
		both restricted and free importable capital goods appropriate information should be given in both the columns).
	</div>
	<div>
		15. Whether product to be exported is restricted for export - Yes/No
		(If yes, enclose copy of EFC apprval from DGF Hqrs.)
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>16.</td>
			<td colspan="3">Details of Duty</td>
		</tr>
		<tr>
			<td></td>
			<td>Total effecive Cusoms duty on items o be imported (in %)</td>
			<td>CIF value of imports/deemed imports (in Rs.)</td>
			<td>Duty saved amunt (in Rs.)</td>
		</tr>
		<tr>
			<td></td>
			<td>1</td>
			<td>2</td>
			<td>3</td>
		</tr>
	</table>
	<div>
		Note: In case of indigenous sourcing of CG, duty saved is to be calculated on notional customs duty saved on FOR value f capial goods as per Para 5.07 of FTP.
	</div>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>17.</td>
			<td colspan="4">Details of Duty in case of posr-expr EPCG duty credit scrip</td>
		</tr>
		<tr>
			<td></td>
			<td>Total effective Customs duty on items to be imported (in %)</td>
			<td>Basic Customs duty</td>
			<td>CIF value of imports/deemed imports (in Rs.)</td>
			<td>Duy paid  (in Rs.)</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>18.</td>
			<td colspan="4">Details of Export Obligation imposed</td>
		</tr>
		<tr>
			<td></td>
			<td>Total duty saved/duty paid (Rs.)</td>
			<td colspan="2">Specific Export Obligation to be imposed</td>
			<td>Average Export Obligation to be imposed</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td>Rs.</td>
			<td>USD</td>
			<td>Rs.</td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>19.</td>
			<td>
				Address of the factory/premises of the application or the supporting manufacurer where the capital goods to<br/>
				be imported are proposed to be installed
			</td>
		</tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>20.</td>
			<td colspan="3">In case the prposed capital goods sought to be imported are to be used by the supporting manufacturer</td>	
		</tr>
		<tr>
			<td></td>
			<td>a.</td>
			<td>Name</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>b.</td>
			<td>Address</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>c.</td>
			<td>MSME/IEM/LOI/IL Registration No. and date</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>d.</td>
			<td>Products endorsed on MSME/LOI/IL/IEM</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>e.</td>
			<td>Excise Registration No. and issuing authoriy, (if applicable)</td>
			<td></td>
		</tr>
	</table>
	<table class="table table-bordered" style="width: 950px">
		<tr>
			<td>21.</td>
			<td>
				Postal address f the jurisdictional Central Excise Auhoriy in whose jurisdiction factory/premises of the<br/>
				applicant/supporting manufacurer where the capital goods to be imported are proposed to be installed.
			
			</td>	
		</tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
	</table>
	<div style="text-align: center;font-weight: bold;height: 30px;">DECLARATION/UNDERTAKING</div>
	<div>
		<ol>
			<li>I / We hereby declare that the particulars and the statements made in this application are true and correct to the best of my/our knowledge and belief and nothing has been concealed or held there from and if found incorrect or false will render me/us liable for any penal action or other consequences as may be prescribed in law or otherwise warranted.</li>
			<li>I / We undertake to abide by the provisions of the Foreign Trade (Development and Regulation) Act, 1992, the Rules and Orders framed there under, the Foreign Trade Policy, the Handbook of Procedures and the ITC(HS) Classification of Export & Import Items.</li>
			<li>I / We hereby certify that none of the Proprietor / Partner(s) / Director(s) / Karta / Trustee of the firm / company, as the case may be, is/are a Proprietor / Partner(s) / Director(s) / Karta / Trustee in any other firm / Company which has come to the adverse notice of DGFT.</li>
			<li>I / We hereby certify that neither the Registered Office/Head Office of the firm/company nor any of its Branch Office(s) / Unit(s) / Division(s) has been declared a defaulter and has otherwise been made ineligible for undertaking import / export under any of the provisions of the Policy.</li>
			<li>I / We hereby certify that our applicant firm/company is NOT currently availing any benefits under Technology Upgradation Fund Scheme (TUFS), administered by Ministry of Textiles, Government of India. (Applicable to zero duty EPCG scheme only)</li>
			<li>I / We hereby certify that our applicant firm/company has NOT availed and shall not avail the benefit of Status Holder Incentive Scheme under Para 3.16 of FTP in the current year. (Applicable to zero duty EPCG scheme only)</li>
			<li>I / We hereby declare that I/we have perused the list of SCOMET items as contained in the Appendix 3 to the Schedule 2 of the ITC (HS) Classifications of Export-Import Items, 2004-09 and that the item(s) exported / proposed to be exported does not fall within this list and that I/ We agree to abide by the provisions of the Policy for export of SCOMET items contained in the Foreign Trade Policy, Schedule 2 of ITC (HS) and the Handbook of Procedures (Vol.1), irrespective of the scheme under which the item is exported / proposed to be exported.</li>
			<li>I / We declare that no export proceeds are outstanding beyond the prescribed period as laid down by the RBI, or such extended period for which RBI permission has been obtained.</li>
			<li>I / We hereby declare that the capital goods/spares sought for import in the application are actually required for use at pre production/production/post production stages for the export product(s) or for rendering services for fulfillment of export obligation.</li>
			<li>I / We hereby declare that in respect of goods for which nexus is not established at a later date, I / We shall pay to the Government Customs duty saved together with 15% interest on such imported goods which are found having no relation with product exported or service rendered.</li>
			<li>I / We hereby declare that in case of import of refurbished/reconditioned spares, the refurbished/reconditioned spares have a residual life which is not less than 80% of the life of the original spares.</li>
			<li>I / We hereby declare that I / We do not come under the purview of Service Tax and therefore are not registered with the Service Tax Cell of the jurisdictional Central Excise Authorities. (in case of Service Providers who are not covered under service tax)</li>
			<li>I / We hereby declare that I/We shall not exceed the SSI investment limit in plant and machinery after making imports under the EPCG Authorisation. (applicable in cases of imports made by SSI sector)</li>
			<li>I / We hereby declare that the import of capital goods shall be used for building and operating shopping malls/super markets having a minimum covered area of 1000 sq meters. (Applicable in case of imports made by Retail sector).</li>
			<li>I / We hereby declare that I/We have not made imports under the Technological Upgradation Scheme previously before any Licensing authority and the present imports of Capital Goods to be made under this Scheme (for which this application is made) are more than 10% of the my/our present investment in the plant and machinery. (Applicable in case of imports under EPCG Technological Upgradation Scheme).</li>
			<li>I / We undertake to submit a self certified copy of 'Drug Manufacturing Licence' in case of export of Pharmaceutical Product(s) within a period of three years from the date of issue of EPCG Authorization failing which the Bank Guarantee / Legal undertaking executed / furnished at the time of clearance of Capital Goods with Customs authorities / Regional Authorities of DGFT, as the case may be, is liable to be forfeited / invoked and I / We would be liable to pay Customs Duty saved amount together with applicable interest thereon from the date of first import till the date of final payment.</li>
			<li>I hereby certify that I am authorized to verify and sign this declaration as per Paragraph 9.9 of the Policy. </li>
		</ol>
	</div>
	<div>(Note: Strike out the clause which is not applicable.)</div>
</form>