<div><b>Welcome to SREE IMPEX</b></div>
<br/>
<div>
We, Shree Impex, are Exim Consultants situated adjacent to Kendriya Sadan, Koramangala Bangalore with a full fledged office with a team of experts .We have over 2 decades of experience.
</div><br/>
<b>Why choose Shree Impex:</b><br/><br/>

   Track record of  Shree Impex:<br/><br/>

        1) Beside Kendriya Sadan - JDGFT office.  <br/><br/> 

        2)  Have two decades of serving experience.<br/><br/>

       3) Have full pledged office with experienced staff.<br/><br/>

    4) A modern Office with in-house facilities &and; Dedicated internet.<br/><br/>
    
   <b> What We Do</b><br/><br/>

    Assisting Exporters to Realise Exim Benefits:<br/><br/>

a) IEC  - Importer Exporter Code<br/><br/>

b) EPCG - authorizations,<br/><br/>

c) Advance Audthorizations,<br/><br/>

d) MEIS/ SEIS scrips<br/><br/>

e) discharge of Export Obligations<br/><br/>

f) Chartered EnginnerCertfications,<br/><br/>

g) We are an authorized partner of (n) Code Solutions - A Division of GNFC Ltd., for Issuing Digital Signature Certificates to individuals, Exim Organizations, and Organizations under the IT Act 2000.<br/><br/>